- usr/lib/pkcs11/ica_s390_stdll/ica_specific.c
This solves issue #19 
Signed-off-by: Ingo Tuchscherer <ingo.tuchscherer@linux.vnet.ibm.com>
> Make ica-token analyze the mechanism-information from libica correctly.

- configure.ac
This patch fixes GitHub issue #11
> Update CCA package name in configure.ac

- rpm/opencryptoki.spec
Remove some unnecessary steps from example spec file.
> Remove some unnecessary steps from example spec file

- usr/sbin/pkcsconf/pkcsconf.c
Handle invalid input for slot number argument. Now, accepts only valid
numbers defined by limits.h and exits with error.
This patch fixes GitHub issue #14
> Fix pkcsconf invalid slot number argument.

- usr/lib/pkcs11/common/utility.c
- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
- usr/lib/pkcs11/icsf_stdll/icsf_config_lexer.l
- usr/lib/pkcs11/icsf_stdll/icsf_specific.c
- usr/lib/pkcs11/soft_stdll/soft_specific.c
- usr/sbin/pkcsslotd/lexer.l
In order to have a clean build some warnings had to be taken care of.
Please analyze each commit separately. 
Thanks
> Fix multiple warnings that shown up during make

- rpm/opencryptoki.spec
> Update spec file URL and Source to GitHub

- usr/lib/pkcs11/soft_stdll/soft_specific.c
If OpenSSL is loading an engine, we might end up having an infinite loop, since
the SOFT token doesn't implement RSA encryption/decryption and calls OpenSSL to
solve it. So to fix it, we check if an engine is loaded and, if yes, we set RSA
methods to the default RSA methods.
> SOFT: Fix for the case where an engine is loaded on Openssl

- testcases/misc_tests/threadmkobj.c
- testcases/misc_tests/tok_obj.c
- usr/lib/pkcs11/common/loadsave.c
- usr/lib/pkcs11/common/trace.c
- usr/lib/pkcs11/icsf_stdll/pbkdf.c
- usr/lib/pkcs11/tpm_stdll/tpm_specific.c
- usr/sbin/pkcscca/pkcscca.c
Those warnings appeared only on Ubuntu.
> Fix some warnings regarding unused results

- usr/lib/pkcs11/tpm_stdll/tpm_specific.c
The TPM token code uses some global variables to track the storage
root key, root public & private keys, and leaf public & private keys
from the TPM. These variables are not properly reinitialized during
unload and reload of the module.
Patch applied from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=603104
This patch fixes #2
Signed-off-by: David Smith <dds@google.com>
> Reset TPM data-structures on init, not just logout.

- ChangeLog
- README.md
- configure.ac
- doc/system_resources
- rpm/opencryptoki.spec
> Bumping up to version-3.8.0

- usr/lib/pkcs11/api/api_interface.c
- usr/lib/pkcs11/icsf_stdll/new_host.c
> Fix spelling errors.

- usr/lib/pkcs11/common/obj_mgr.c
- usr/lib/pkcs11/common/template.c
During development for a future enhancement, I noticed a few bugs and shortcomings in common code.
> Miscelaneous fixes in common code

- man/man5/opencryptoki.conf.5.in
- testcases/ock_tests.sh.in
Updated opencryptoki.conf man page
Improved ock_tests to run test cases to multiple tokens in parallel.
> Multi token instance - test tool / description - v2

- ChangeLog
- README.md
- configure.ac
- rpm/opencryptoki.spec
> Bumping up to version-3.8.2

- man/man1/pkcsep11_session.1.in
> EP11: Editorial changes for the pkcsep11_session man page

- usr/lib/pkcs11/common/loadsave.c
- usr/lib/pkcs11/common/lock_btree.c
- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
- usr/lib/pkcs11/ica_s390_stdll/ica_specific.c
- usr/sbin/pkcsep11_session/pkcsep11_session.c
Fix logic for getting and releasing locks when DestroyObject is called and fix some compiler warnings.
> Fix logic and warnings

- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
true -> cktrue. cktrue is already used in other places.
> Dont define 'true': it is reserved by stdbool.h

- configure.ac
> autotools update

- usr/lib/pkcs11/ica_s390_stdll/ica_specific.c
> Fix C_GetMechanismList return value for icatok

- usr/lib/pkcs11/common/new_host.c
> Fix NULL-ptr deref crashes in DEBUG build

- usr/lib/pkcs11/common/key_mgr.c
- usr/lib/pkcs11/common/mech_aes.c
- usr/lib/pkcs11/common/mech_des.c
Cleanse areas that contain keys before freeing them.
Also don't use realloc to increase areas that contain keys.
This fixes issue https://github.com/opencryptoki/opencryptoki/issues/32
> Harden key wrapping

- usr/lib/pkcs11/cca_stdll/cca_specific.c
- usr/lib/pkcs11/ica_s390_stdll/ica_specific.c
- usr/lib/pkcs11/soft_stdll/soft_specific.c
> rsa verify must assume an invalid signature if rsa op fails

- usr/sbin/pkcsslotd/slotmgr.c
The current implementation creates the pid file of the
pkcsslotd demon as one of the last steps of the slot
demons startup. It's done after the parent has spawned
away the child which will become the demon when this child
is nearly done with initialization. At this time the
parent has already terminated.
However, systemd expects to find the pid file when the
parent terminates. So here is now a patch which moves
the creation of the pid file into the parent code. Now
the pid file is created after the child has been forked
in the parent process short before it calls exit().
Signed-off-by: Harald Freudenberger <freude@linux.ibm.com>
> pkcsslotd: adapt pid file creation on demonize for systemd

- usr/lib/ep11_stdll/ep11_specific.c
To allow configurations where mixed CEX levels are online and APQN_ANY is used or an APQN whitelist is specified with APQNs of different CEX levels included, I have reworked the EP11 version query.
I am now building a list of CEX levels of the configured APQNs (ANY or whitelist). All APQNs of the same  CEX level must still have the same firmware level. APQNs of different CEX levels can have different firmware levels.
Checking if a certain feature is supported by all configured APQNs is slightly more complicated now, since you need to check for the minimum firmware level per CEX level. A helper function is added to do this more easily.
> RFC: Enhance version query to support mixed CEX levels

- usr/lib/common/defs.h
- usr/lib/common/new_host.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/icsf_specific.c
- usr/lib/icsf_stdll/new_host.c
- usr/sbin/pkcsconf/pkcsconf.c
This fixes issue https://github.com/opencryptoki/opencryptoki/issues/171
> Remove definition of MAX_SLOT_ID and use NUMBER_SLOTS_MANAGED instead

- testcases/common/common.c
- testcases/crypto/aes_func.c
- testcases/crypto/rsa_func.c
- testcases/crypto/rsaupdate_func.c
- testcases/pkcs11/sess_perf.c
- usr/lib/cca_stdll/cca_specific.c
- usr/lib/common/key.c
- usr/lib/common/key_mgr.c
- usr/lib/common/mech_ec.c
- usr/lib/common/mech_rsa.c
- usr/lib/common/mech_ssl3.c
- usr/lib/common/object.c
- usr/lib/common/sign_mgr.c
- usr/lib/common/utility.c
- usr/lib/common/verify_mgr.c
- usr/lib/icsf_stdll/pbkdf.c
- usr/lib/tpm_stdll/tpm_util.c
- usr/sbin/pkcscca/pkcscca.c
- usr/sbin/pkcsslotd/garbage_linux.c
Lots of small and mostly trivial fixes for the issues found by the coverty scan.
Take you time to review....
> Coverty fixes

- usr/lib/common/loadsave.c
- usr/lib/common/new_host.c
- usr/lib/common/obj_mgr.c
- usr/lib/common/utility.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/icsf_specific.c
- usr/lib/icsf_stdll/new_host.c
- usr/lib/tpm_stdll/tpm_specific.c
- usr/sbin/pkcsslotd/mutex.c
- usr/sbin/pkcsslotd/slotmgr.c
Resolve issue https://github.com/opencryptoki/opencryptoki/issues/35 .
> Check XProckLock return values

- testcases/pkcs11/sess_mgmt.c
- usr/lib/common/mech_ssl3.c
> Last fixes for 3.11

- ChangeLog
- README.md
- configure.ac
- man/man5/opencryptoki.conf.5.in
- rpm/opencryptoki.spec
- usr/sbin/pkcsslotd/opencryptoki.conf
Did i miss anything in the changelog entry ?
> 3.11 release commit

- usr/lib/common/mech_aes.c
- usr/lib/common/mech_des3.c
- usr/lib/common/mech_md2.c
- usr/lib/common/mech_md5.c
- usr/lib/common/mech_rsa.c
- usr/lib/common/mech_sha.c
- usr/lib/common/mech_ssl3.c
- usr/lib/ica_s390_stdll/ica_specific.c
- usr/lib/soft_stdll/soft_specific.c
Fixes: https://github.com/opencryptoki/opencryptoki/issues/250
> Replace memcmp by CRYPTO_memcmp when comparing tags

- usr/lib/ep11_stdll/ep11_specific.c
With just toleration support of new crypt cards, new crypto cards are reported as the last known crypto card version. E.g. a CEX7 card is reported as CEX6, when CEX6 is the last known crypto card version.
The EP11 token checks the card versions and needs to distinguish tolerated cards from supported cards. New (tolerated) crypto cards may have different API and firmware versions, and thus need to be
handled differently.
> EP11: Support tolerated new crypto cards

- usr/sbin/pkcsconf/pkcsconf.c
See issue https://github.com/opencryptoki/opencryptoki/issues/230 .
> Inform the user about required pkcs11 group membership

- usr/include/apictl.h
- usr/lib/api/api_interface.c
- usr/lib/api/apiproto.h
- usr/lib/api/apiutil.c
- usr/lib/common/btree.c
- usr/lib/common/h_extern.h
- usr/lib/common/host_defs.h
- usr/lib/common/lock_btree.c
- usr/lib/common/new_host.c
- usr/lib/common/utility.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/new_host.c
A series of fixes/changes to make Opencryptoki thread save.
> RFC: Make OCK thread save

- testcases/common/common.c
- testcases/include/regress.h
- testcases/login/digest_init.c
- testcases/login/init_pin.c
- testcases/login/init_tok.c
- testcases/login/login.c
- testcases/login/login_flags.c
- testcases/login/set_pin.c
- testcases/misc_tests/speed.c
- testcases/misc_tests/threadmkobj.c
- testcases/misc_tests/tok_des.c
- testcases/misc_tests/tok_obj.c
- testcases/misc_tests/tok_obj2.c
- testcases/misc_tests/tok_rsa.c
- testcases/pkcs11/hw_fn.c
I can't test with gcc 10, but this should fix the build errors.
Fixes: https://github.com/opencryptoki/opencryptoki/issues/271
> Fix build issue with gcc 10 and -fno-common

- usr/lib/common/trace.c
For multithread debugging the opencryptoki traces now have an
additional field 'tread id' which is simple the gettid() value.
Signed-off-by: Harald Freudenberger <freude@linux.ibm.com>
> Add thread id to the trace line output.

- usr/lib/common/key.c
- usr/lib/ep11_stdll/ep11_specific.c
Fix typos in TRACE messages, add parentheses in constant definitions, and remove some superfluous code in rsa_ec_generate_keypair().
> Misc cleanup

- usr/lib/common/lock_btree.c
- usr/lib/common/lock_sess_mgr.c
lock_btree.c and lock_sess_mgr.c rework - version 2
> Btree and sess mgr lock rework 2

- ChangeLog
- README.md
- configure.ac
- rpm/opencryptoki.spec
- usr/sbin/pkcsslotd/opencryptoki.conf
.. make lock built the default.
> version 3.13

- usr/lib/tpm_stdll/tpm_openssl.c
- usr/lib/tpm_stdll/tpm_specific.c
- usr/lib/tpm_stdll/tpm_specific.h
Fixes https://github.com/opencryptoki/opencryptoki/issues/299
> TPM: Fix segfault in C_SetPin

- usr/sbin/p11sak/p11sak.c
> p11sak: fix typo in help

- usr/lib/common/mech_ec.c
introduced with commit 31f3379a31c1f892fafd30348fba8608142ceec4
> Fix endian bug in X9.63 KDF

- usr/lib/tpm_stdll/tpm_specific.c
I spent a while trying to understand how the object files [are stored](http://trousers.sourceforge.net/pkcs11.html) when using the TPM token, and was confused about what the `MK_PRIVATE` file does, because it didn't quite correspond to any documentation.
As far as I can tell, it _doesn't_ do anything at all. It is generated but never used. (`master_key_private` hasn't been used for anything since commit 78acdd720019ed3c901f39eaa8c5a61a01b84488 and is only referenced from the "load" and "store" functions. The compiler did not disagree with its removal.)
> TPM: remove loading and generation of MK_PRIVATE

- testcases/pkcs11/attribute.c
- usr/lib/common/template.c
Some ULONG attributes are always stored as 32 bit ULONG, while others are stored in the length that CK_ULONG is on the systems architecture. I.e. on a 64 bit system a CK_ULONG is 64 bit in size, while on a 32 bit system it is 32 bit in size.
The same logic must also be used when unflattening attribute-array elements, when an element is such an attribute that is always stored as 32 bit ULONG.
Also fix an error when flattening an attribute-array element.
> Fix attribute-array flatten and unflatten

- Makefile.am
- testcases/misc_tests/p11sak_test.sh
Added test cases for the p11sak tool incl. Changes for CI integration in the makefile. Signed-off-by: Matthias Reumann <matthias.reumann1@ibm.com
> Added test cases for the p11sak tool

- usr/lib/ep11_stdll/ep11_specific.c
When importing public or private EC keys that uses unsupported curves (i.e. Edwards or Montgomery curves), it depends on the EP11 firmware level if the import fails and how it fails. Even if the import works, the imported EC key would still not be usable with any mechanisms afterwards, if the underlying firmware does not support the curve.
Check the curve type when importing EC keys in the EP11 token, and allow Edwards or Montgomery curves only if all configured APQNs support it. Fail with CKR_CURVE_NOT_SUPPORTED if not.
> EP11: Check if curve is supported on EC key import via C_CreateObject

- testcases/crypto/abfunc.c
- testcases/crypto/crypto.mk
- testcases/ock_tests.sh.in
- usr/include/pkcs11types.h
- usr/lib/common/key.c
- usr/lib/common/obj_mgr.c
- usr/lib/common/p11util.c
- usr/lib/ep11_stdll/ep11_specific.c
- usr/sbin/pkcsslotd/pkcsslotd.mk
Add support for attribute bound keys to EP11.
> EP11: Attribute bound keys

- testcases/crypto/abfunc.c
- usr/lib/ep11_stdll/ep11_specific.c
CI discovered that ECDH1 derivation does not work with AB keys on pre-CEX7 cards.  Fix and fail with CKR_MECHANISM_INVALID in that case.
> Fix AB for pre CEX7 cards

- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ica_s390_stdll/ica_specific.c
- usr/lib/soft_stdll/soft_specific.c
From PKCS#11: "pPublicData: pointer to other party’s EC public key value. A token MUST be able to accept this value encoded as a raw octet string (as per section A.5.2 of [ANSI X9.62]). A token MAY, in addition, support accepting this value as a DER-encoded ECPoint (as per section E.6 of [ANSI X9.62]) i.e. the same as a CKA_EC_POINT encoding."
It can happen that the specified  public data looks like it would be an DER encoded ECPoint, but in fact it is not. This happens when the public data starts with 0x04 (either an OCTET STRING DER tag, or a point conversion indicator byte for "uncompressed") followed by a byte who's value is 2 less than the length of the public data. That way the second byte looks like a valid single-byte length octet of a DER encoded tag.
Add an additional check if …
> Fix detection of DER encoded or raw ECDH public data

- testcases/crypto/rsa_func.c
- testcases/crypto/rsaupdate_func.c
- usr/lib/common/asn1.c
- usr/lib/common/key_mgr.c
- usr/lib/common/mech_ec.c
- usr/lib/common/mech_md2.c
- usr/lib/common/mech_md5.c
- usr/lib/common/mech_rsa.c
- usr/lib/common/mech_sha.c
- usr/lib/common/obj_mgr.c
- usr/lib/soft_stdll/soft_specific.c
Some minor leaks (in the test cases, or in error cases), but also some not so minor leaks that happen unconditionally.....
> Fix memory leaks

- usr/lib/icsf_stdll/icsf.c
- usr/lib/icsf_stdll/icsf_specific.c
- usr/lib/icsf_stdll/new_host.c
Some test cases with specific EC curves and RSA keys still fail, but I fear that this is due to ICSF not supporting those EC curves and RSA keys.
> Minor ICSF Fixes

- testcases/crypto/abfunc.c
This is a simple helper commit to track down a problem sporadically reported by our CI system.
> Dump keys on AB wrap/unwrap errors

- testcases/crypto/abfunc.c
To further track down errors in AB-tests, we also dump the SPKIs of the
involved keys and capture them in the CI.
> [TEST: abfunc] Dump SPKIs on failure

- usr/lib/ep11_stdll/ep11_specific.c
After a key generation, key import, derive, or unwrap operation, retrieve some EP11 specific attributes from the key blob, and update/set these attributes in the Opencryptoki object as well.
The EP11 specific attributes can be specified by an application in the template for object creation, import, derive, or unwrap, and they will then be contained in the EP11 key blob as well. With this change, EP11 specific attributes that have not been specified and got a default value by EP11, are now also available
as PKCS#11 attributes.
> EP11: Update EP11 specific attributes from key blob

- testcases/crypto/abfunc.c
Fixes: https://github.com/opencryptoki/opencryptoki/issues/429
> TESTCASES: Add license header to abfunc.c

- .travis.yml
> travis: adapt ppc64le targets

- usr/lib/api/api_interface.c
- usr/lib/api/apiutil.c
- usr/lib/api/socket_client.c
- usr/lib/common/asn1.c
- usr/lib/common/event_client.c
- usr/lib/common/key.c
- usr/lib/common/loadsave.c
- usr/lib/common/mech_aes.c
- usr/lib/common/mech_des.c
- usr/lib/common/mech_des3.c
- usr/lib/common/mech_ec.c
- usr/lib/common/mech_list.c
- usr/lib/common/mech_ssl3.c
- usr/lib/common/new_host.c
- usr/lib/common/obj_mgr.c
- usr/lib/common/shared_memory.c
- usr/lib/common/utility.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/icsf.c
- usr/lib/icsf_stdll/icsf_specific.c
- usr/lib/icsf_stdll/new_host.c
- usr/lib/icsf_stdll/pbkdf.c
- usr/sbin/p11sak/p11sak.c
- usr/sbin/pkcsconf/pkcsconf.c
- usr/sbin/pkcsicsf/pkcsicsf.c
- usr/sbin/pkcsslotd/garbage_linux.c
- usr/sbin/pkcsslotd/socket_server.c
- usr/sbin/pkcstok_migrate/pkcstok_migrate.c
For a list of findings, see opencryptoki-3.16.0-covscan.log attached to https://github.com/opencryptoki/opencryptoki/issues/422
Not all findings are addressed, especially those in the testcases are ignored for now.
> Fix coverty scan findings

- Makefile.am
- testcases/ciconfig.sh
To be reverted once we have corrected the EP11 session issue in the CI.
> CI: Temporarily disable slot 42

- usr/lib/common/loadsave.c
Functions encrypt_data() and decrypt_data() would only be used for tokens that are no secure-key tokens, and use an encryption algorithm for the MK_USER/MK_SO file other than CKM_DES3_CBC (for the old token format only).
The only token that uses anything other than CKM_DES3_CBC is the TPM token, but it is flagged as secure key token. The ICSF token specifies 0 as mechanism, but it does not use this code path at all.
In general, there should be no reason why the token's own encryption and decryption functions should be used instead of Opencryptoki's software implementation (based on OpenSSL). Also the removed functions do not provide any additional mechanisms than CKM_DES3_CBC and CKM_AES_CBC, which are also covered by the general software implementation.
Besides that, there was a memory …
> COMMON: Remove unused code

- testcases/ciconfig.sh
Test with the new token version every second day.
> [CI] Alternate token directory versions every day

- usr/sbin/pkcstok_migrate/pkcstok_migrate.c
Fix some problems of pkcstok_migrate to maybe get if finally clean for the new OCK release....
> A couple of pkcstok_migrate fixes

- usr/sbin/p11sak/p11sak.c
> Fix p11sak config file handling

- usr/lib/api/socket_client.c
Avoid that the event thread writes trace messages while it is
enabled for thread cancellation. This might leave the trace mutex in
the locked state and cause subsequent trace calls to lock forever
(e.g in stop_event_thread() right after canceling the thread).
Disable cancellation right at the beginning of the thread function,
and disable it before calling a trace function or leaving the loop.
Also make sure that the cleanup handler is registered and the
cancellation type is set before initially enabling cancellation.
> API: Avoid deadlock when stopping event thread

- ChangeLog
- README.md
- configure.ac
- rpm/opencryptoki.spec
- usr/sbin/pkcsslotd/opencryptoki.conf
> Bumping up to version-3.18.0

- usr/sbin/pkcsslotd/socket_server.c
The AP device driver may send an 'change' udev events for AP cards and queues whenever a card or queue is configured offline or online, or set soft-offline or soft-online via chzcrypt.
Treat such events as APQN ADD or REMOVE events and pass it to the applications, similar to bind and unbind udev events.
> pkcsslotd: Add support for AP queue 'change' udev events

- usr/lib/common/mech_openssl.c
- usr/lib/ica_s390_stdll/ica_specific.c
In OpenSSL 3.0 the RSA key gen algorithm has been changed and can now fail to generate a key. Retry up to 10 times in such a case.
> COMMON: Retry RSA key gen if it fails with OpenSSL 3.0

- usr/lib/api/policy.c
- usr/lib/api/statistics.c
- usr/lib/api/statistics.h
- usr/lib/common/asn1.c
- usr/lib/common/attributes.c
- usr/lib/common/decr_mgr.c
- usr/lib/common/encr_mgr.c
- usr/lib/common/key.c
- usr/lib/common/loadsave.c
- usr/lib/common/new_host.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/icsf_specific.c
- usr/sbin/p11sak/p11sak.c
- usr/sbin/pkcsslotd/socket_server.c
- usr/sbin/pkcsstats/pkcsstats.c
- usr/sbin/pkcstok_migrate/pkcstok_migrate.c
Closes: https://github.com/opencryptoki/opencryptoki/issues/562
> Fixes for coverty scan findings

- usr/lib/cca_stdll/cca_specific.c
- usr/lib/common/h_extern.h
- usr/lib/common/loadsave.c
- usr/lib/common/obj_mgr.c
- usr/lib/common/pkcs_utils.c
- usr/lib/ep11_stdll/ep11_specific.c
A few things that were identified during development work.
> Misc fixes

- .travis.yml
'make check' is currently not run in the CI, so lets run it at least in travis.
> travis: run 'make check' during travis execution.

- Makefile.am
- testcases/misc_tests/pkcsconf_test.sh
The PR #565 unfortunately introduced a ci-breakage. This PR contains the required fixes to make ci runable again.
> Fixes for ci

- .travis.yml
- testcases/misc_tests/p11sak_test.sh
- usr/sbin/p11sak/p11sak.c
Todays CI run showed some errors caused by p11sak.
> p11sak fixes

- opencryptoki_tok.map
- testcases/pkcs11/sess_mgmt.c
- usr/include/pkcs11types.h
- usr/include/stdll.h
- usr/lib/api/api_interface.c
- usr/lib/common/h_extern.h
- usr/lib/common/lock_sess_mgr.c
- usr/lib/common/new_host.c
- usr/lib/common/sess_mgr.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/new_host.c
The changes in the new_host.c files are all the same in all 3 files.
Similar, the changes in sess_mgr.c and lock_sess_mgr.c are also the same.
So you only need to review one of each.
> Add support for C_SessionCancel (PKCS#11 v 3.0)

- man/man1/p11sak.1.in
- testcases/misc_tests/p11sak_test.sh
- usr/sbin/p11sak/p11sak.c
- usr/sbin/p11sak/p11sak.h
Add support for generating, listing and deleting AES-XTS keys.
> p11sak: Add support for the AES-XTS key type

- usr/lib/common/host_defs.h
- usr/lib/common/obj_mgr.c
- usr/sbin/p11sak/p11sak.c
- usr/sbin/pkcstok_migrate/pkcstok_migrate.c
Reported by @ngothan in https://github.com/opencryptoki/opencryptoki/issues/625
> Coverty scan fixes

- man/man1/p11sak.1.in
- usr/sbin/p11sak/p11sak.c
- Display key type with remove-key user prompt
- Allow to specify label for public and private key objects separately
- Misc fixes and adjustments
> p11sak: minor enhancements

- README.md
- configure.ac
- rpm/opencryptoki.spec
- tools/tools.mk
Fixes https://github.com/opencryptoki/opencryptoki/issues/635 from @mhartmay
> configure: Support cross compilation

- usr/lib/ep11_stdll/ep11_specific.c
Using an existing and valid protected key attached to a key object is not dependent on the session state. Only if the protected key must be (re-)created (secure key to protected key transformation), a proper session state is required.
PKCS#11-UG states:
_"A session can be a read/write (R/W) session or a read-only (R/O) session. Read/write and read-only refer to the access to token objects, not to session objects. In both session types, an application can create, read, write and destroy session objects, and read token objects. However, only in a read/write session can an application create, modify, and destroy token objects."_
Allow the transformation of a key object into a protected key for session objects also in a read-only session. As per above, session objects can be updated in …
> EP11: Correct precondition checks for protected key usage and creation

- testcases/ciconfig.sh
@juergenchrist thanks for noticing this.
> ci: Fix genlatestep11cfg() function to add option to config file

- usr/lib/icsf_stdll/icsf.c
> ICSF fixes

- usr/lib/api/policy.c
AES-XTS keys use 2 keys, and thus the AES-XTS mechanisms reports the minimum and maximum key size in the mechanism info as 32 - 64 bytes (256 - 512 bits). However, the strength of such an AES-XTS key is just the half of its size, i.e. a 256 bit AES-XTS key has a strength of 128 bits only. Likewise a 512 bit AES-XTS key has a strength of 256 bits.
While the checking of the key strength when using an AES-XTS key is done correctly, the supported minimum key size in the mechanism list is not updated according to the minimum strength policy setting. So, if a minimum strength of 256 bits is configured, then the minimum key size of the AES-XTS mechanisms must be adjusted to 64 bytes (512 bits).
> policy: Fix update of mechanism info for AES-XTS mechanisms

- usr/lib/ica_s390_stdll/ica_specific.c
The ICA token uses libica to generate RSA keys in CRT format. That way, the public key components n and e, as well as the private CTR components p, q, dp, dq, and qInverse are available, but not the private exponent d.
Calculate the private exponent d from the modulus n, the public exponent e, and the private key components p and q as follows:
ϕ(n) = (p − 1) * (q − 1) = n − p − q + 1. Then d = e ^−1 mod ϕ(n)
That way, an RSA key generated by the ICA token has all private key components, the mod-expo components as well as the CRT components.
> ICA: Calculate private exponent when generating RSA keys

- usr/lib/cca_stdll/cca_specific.c
The CCA host library needs an uncompressed EC point in the key value structure when importing an EC public key. Uncompress the EC point using OpenSSL in case CKA_EC_POINT contains an EC point in compressed form.
> CCA: Support EC public key import with compressed EC point

- testcases/README
Closes: https://github.com/opencryptoki/opencryptoki/issues/666
> testcases: Update testcases README file

- usr/lib/cca_stdll/cca_specific.c
- usr/lib/ep11_stdll/ep11_specific.c
The CCA token queries the serial number of the current CCA adapter during token initialization. This serial number is then later used to select the adapter during cca_iterate_adapters().
Unfortunately, the underlying adapter may change during runtime, and thus the serialno may change as well. Query the current serialno freshly within cca_iterate_adapters() and not depend on a remembered, and now possibly incorrect serialno.
> CCA: Don't remember serialno of adapter as it can change during runtime

- usr/sbin/p11sak/p11sak.c
When importing a x509 certificate, supply the DER encoded serial number for the CKA_SERIAL_NUMBER attribute. When displaying the CKA_SERIAL_NUMBER use a custom print routine to decode the DER encoded serial number and print the raw serial number.
> p11sak: CKA_SERIAL_NUMBER contains the DER encoded serial number

- usr/lib/api/api_interface.c
Opencryptoki initializes OpenSSL as part of its own initialization in C_Initialize. During OpenSSL initialization, the OpenSSL config file is evaluated, and engines or providers may be loaded and initialized.
An engine or provider may itself use Opencryptoki and thus may call C_Initialize as part of its initialization. This leads to a recursive call of C_Initialize and thus to a deadlock because C_Initialize locks the global mutex while it initializes.
Add special handling to allow recursive calls of C_Initialize coming from the OpenSSL initialization triggered by Opencryptoki. Move the OpenSSL initialization to the very beginning of C_Initialize, and release the global mutex before calling OPENSSL_init_crypto. On return from OPENSSL_init_crypto, check if Opencryptoki has been initialized …
> API: Special handling for recursive calls of C_Initialize

- usr/lib/common/mech_rsa.c
Take the implementation of OpenSSL function RSA_padding_check_PKCS1_type_2() in crypto/rsa/rsa_pk1.c instead of ossl_rsa_padding_check_PKCS1_type_2(), since the latter leaks the message size.
Fixes: https://github.com/opencryptoki/opencryptoki/issues/731
> Fixes for Marvin attack

- usr/lib/ep11_stdll/ep11_specific.c
Provides some bugfixes related to ep11 pkey support.
> Pkey bugfixes

- usr/lib/common/loadsave.c
- usr/lib/common/mech_rng.c
- usr/lib/common/pkcs_utils.c
Closes: https://github.com/opencryptoki/opencryptoki/issues/782
> Fix errors reported by covscan

- testcases/crypto/ec_func.c
Some tests can never run, regardless of what the token supports or not. Don't produce SKIP messages for those to reduce the output size.
> TESTCASES: Remove unnecessary SKIP messages for test that can never run

- usr/lib/common/pkey_utils.c
Let s390_pcc return the condition code of the PCC instruction. Also fix the error handling in the calling functions.
> COMMON: correct rc handling with s390_pcc function

- testcases/crypto/aes_func.c
To allow running the testcase concurrently against the same token, generate a unique name, so that one process does not find another process's token object, because this would cause the testcase to fail, although its not a real failure, just an effect of running concurrently.
> TESTCASES: Generate unique label for do_EncryptDecryptAESPkey() test

- usr/lib/cca_stdll/cca_mkchange.c
- usr/lib/common/mech_ec.c
- usr/lib/ep11_stdll/ep11_login.c
- usr/lib/ep11_stdll/ep11_session.c
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ep11_stdll/ep11_specific.h
- usr/lib/ica_s390_stdll/ica_specific.c
- usr/lib/soft_stdll/soft_specific.c
- usr/sbin/p11sak/p11sak.c
- usr/sbin/pkcshsm_mk_change/pkcshsm_mk_change.c
Fixes for findings found by clang's code checker tool.
> Fix code scanner findings

- testcases/misc_tests/obj_mgmt.c
- testcases/misc_tests/obj_mgmt_lock.c
- testcases/misc_tests/tok2tok_transport.c
- testcases/ock_tests.sh.in
- testcases/pkcs11/destroyobjects.c
- testcases/pkcs11/gen_purpose.c
- usr/lib/ep11_stdll/ep11_specific.c
This pr collects the findings from the opencryptoki 3.24 test. More commits may follow.
> Collect findings from opencryptoki 3.24 test

- usr/lib/common/mech_openssl.c
- usr/lib/soft_stdll/soft_specific.c
The newest OQS-provider does no longer support the round 2 and 3 dilithium algorithms, only the standardized variants (i.e. ML-DSA). However, the current check only checked if the algorithm OID is known by OpenSSL (which is still the case), but not if the algorithm is really supported.
Add a check to fetch the algorithm to verify if the algorithm is really supported to avoid failures.
Don't report the CKM_IBM_DILITHIUM mechanism supported if none of the round 3 variants are supported by the OQS-provider.
Note that OpenCryptoki currently does not yet support the standardized ML-DSA algorithms, only the round 2 and 3 variants.
> SOFT: Correct check for PQC algorithm support

- usr/lib/cca_stdll/cca_specific.c
- usr/lib/common/key.c
- usr/lib/common/key_mgr.c
- usr/lib/ep11_stdll/ep11_specific.c
Attribute CKA_IBM_PROTKEY_EXTRACTABLE is set to FALSE as default for key objects, so consequently set CKA_IBM_PROTKEY_NEVER_EXTRACTABLE to TRUE as default as well.
When CKA_EXTRACTABLE or CKA_IBM_PROTKEY_EXTRACTABLE is set to TRUE, then make sure CKA_NEVER_EXTRACTABLE or CKA_IBM_PROTKEY_NEVER_EXTRACTABLE respectively is set to FALSE.
> COMMON: Fix setting of CKA_IBM_PROTKEY_NEVER_EXTRACTABLE and CKA_NEVER_EXTRACTABLE

- usr/lib/ep11_stdll/ep11_specific.c
In case attributes CKA_TOKEN and/or CKA_PRIVATE are changed (only allowed during C_CopyObject, but not via C_SetAttributeValues), special checking is required in regards of session bound keys. In case strict session mode, VHSM mode or FIPS session mode is active, the changed attributes may cause the key object to be expected to be bound to a different EP11 session as it currently is. Check if the key object is bound to the expected session, and fail if not. This prevents to have inconsistent sessions of key objects.
Note: As of now, EP11 does not support/allow to change key objects in regards of the session they are bound to, so the only option currently is to fail.
> EP11: Check session-bound keys when CKA_TOKEN or CKA_PRIVATE is changed

- Makefile.am
- configure.ac
- man/man1/p11kmip.1.in
- man/man5/p11kmip.conf.5.in
- testcases/misc_tests/p11kmip_test.sh
- usr/sbin/p11kmip/p11kmip.c
- usr/sbin/p11kmip/p11kmip.h
- usr/sbin/p11kmip/p11kmip.mk
- usr/sbin/p11sak/p11sak.c
- usr/sbin/p11sak/p11sak.h
- usr/sbin/p11sak/p11sak.mk
- usr/sbin/p11sak/p11tool.c
- usr/sbin/p11sak/p11tool.h
> P11SAK/P11KMIP: Refactor code to extract commonly used functions

- testcases/misc_tests/p11kmip_test.sh
Fix the logic to re-get the login authorization ID from SKLM in case the login token was expired. This can happen if another system concurrently obtains a login authorization ID from the same server. This revokes all previously login tokens.
Thus, in case a operation with SKLM returns message CTGKM6004E, a new login token must be obtained, and the failed setup step must be repeated with the new login token.
While at it, make sure that the retry loop terminates in case of unrecoverable error situations and make sure RC is set in all such cases.
> TESTCASES: Fix KMIP server setup for p11kmip test

- usr/lib/ep11_stdll/ep11_specific.c
When a Secure Execution guest has multiple domains of the crypto cards, then there is an Ultravisor session per domain. Thus it can not be just checked that the key blob to import is bound the 'the one' UV session, but it can be any of the UV sessions of the domains.
Generate a temporary AES key on each APQN, and check if at least one of the sessions of that temporary keys match the session of the blob to import.
Note that all those UV sessions are logged into all domains of the cards, so it is OK to use a key bound to one of the UV sessions on other domains as well.
> EP11: Support key blob import with multiple domains in a Secure Execution guest

- usr/lib/ep11_stdll/ep11_specific.c
Special handling for mechanisms using C_DeriveKey where the mechanism parameter contains an EP11 secure key blob (i.e. Kyber-KEM): If the EP11 key blob in the mechanism parameter causes m_DeriveKey to return CKR_IBM_WKID_MISMATCH, because the master keys have been changed, then retry the whole operation including the preprocessing. This will then cause the preprocessing to set the EP11 key blob in the mechanism parameter to the re-enciphered secure key blob one.
> EP11: Handle concurrent MK change for Kyber-KEM using C_DeriveKey

- usr/lib/cca_stdll/cca_specific.c
Performing the CCA CSNDEDH verb must be enclosed in a RETRY_NEW_MK_BLOB_START/RETRY_NEW_MK_BLOB_END loop to handle the situation where the EC private key token is already enciphered with the new master key, when a concurrent master key change is ongoing.
While at it, fix other minor findings in the code.
Fixes: a40e798c35ed6904f99e7a1766db916e40642505
> CCA: Fix handling of concurrent master key change for ECDH

- usr/lib/cca_stdll/cca_specific.c
When importing a CCA secure key blob for an AES or AES-XTS key, set the attributes CKA_IBM_PROTKEY_EXTRACTABLE=TRUE and CKA_EXTRACTABLE=TRUE when the secure key blob is a CCA DATA key. CCA DATA keys are always extractable and protected key extractable.
When CIPHER keys are imported, these attributes depends on the flags from within the secure key blob, and are already set accordingly during import.
With this change, AES keys now behave the same as HMAC keys already behave. Both CKA_EXTRACTABLE and CKA_IBM_PROTKEY_EXTRACTABLE are now always set during import according to the flags of the secure key blob (and AES DATA keys are always extractable, because they can not be export restricted).
This inconsistency between import behavior of AES DATA vs CIPHER keys was noticed in the CI runs after …
> CCA: Set CKA_IBM_PROTKEY_EXTRACTABLE during import of AES DATA key blob

- usr/lib/ep11_stdll/ep11_specific.c
In an Secure Execution guest strict-session or VHSM mode only works when using an EP11 host library version 4.1 or later and when all APQNs configured for the token support API ordinal 6 or later.
An EP11 host library version 4.1 or later translates a m_Login() call into a m_LoginExtended() call with XCP_LOGIN_ALG_PRE_F2021 when the API ordinal used is >= 6 and this can be correctly intercepted by the Ultravisor.
Only reject the use of strict-session or VHSM mode in a Secure Execution guest if the requirements are not fulfilled.
Fixes: f24ae99bc150bb9556370bca3668670549c5fafe
> EP11: Version checks for strict-session or VHSM mode in a Secure Execution guest
