opencryptoki/opencryptoki

- .travis.yml
- doc/README-IBM_CCA_users
- testcases/Makefile.am
- testcases/ock_tests.sh.in
Since opencryptoki-3.0 the file pk_config_data was replaced by the
opencryptoki.conf file. The ock_tests.sh script was still depending
on the pk_config_data file to read slots number to execute.
This patch fixes GitHub issue #12
> Remove dependence of pk_config_data in ock_tests.sh

- usr/lib/pkcs11/icsf_stdll/icsf.c
- usr/lib/pkcs11/icsf_stdll/icsf_specific.c
While performing ec tests on ICSF token ($ ./testcases/crypto/ec_tests
-slot 5) we're having a segmentation fault. This is related to the case
when length_only attribute is set, so the signature shouldn't be done
and just the signature length should be returned, or for the case when
the signature is invalid, CKR_SIGNATURE_INVALID should be returned.
Fix for issue #18
> Fix segfault on ec_test

- misc/Makefile.am
- misc/tmpfiles.conf.in
Add support to create configuration file for creation, deletion and cleaning
of volatile and temporary files in systemd.
The tmpfiles.d/opencryptoki.conf file will be created automatically during
compilation time based on enabled tokens in configure. The output will be
installed in default systemd-tmpfiles path structure, described here [1].
[1] https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html
This patch fixes #25
> Add support to systemd-tmpfiles config file.

- .travis.yml
- testcases/ock_tests.sh.in
Root user should be able to build and run opencryptoki without being part of
group pkcs11. Only non-root users should be in the pkcs11 group.
> Fix ock_test to not check if root is in group pkcs11

- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
When the ep11 config file contains an APQN_WHITELIST,
but the list is not terminated with the END keyword,
then pkcsconf -t terminates with a segmentation fault.
This fix checks for end-of-file at various states during
parsing and returns an appropriate error.
> Fix bug when parsing the ep11 config file

- doc/opencryptoki-howto.md
The '#include "slotmgr.h"' is not needed in the sample code, as well
as 'Slot_Mgr_Shr_t  *shmp = NULL;'. File slotmgr.h is not installed
into /usr/include/opencryptoki, so compiling this sample would not
be possible outside of the source tree.
> Remove unneeded '#include "slotmgr.h"' in sample

- usr/lib/pkcs11/common/mech_dsa.c
- usr/lib/pkcs11/common/obj_mgr.c
- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
- usr/lib/pkcs11/ep11_stdll/new_host.c
- usr/lib/pkcs11/ica_s390_stdll/ica_specific.c
Test complains about different printouts for the very same info.
So for example the mechanism value is sometimes printed as %ld
sometimes %lx and sometimes 0x%lx or 0x%08lx. So here is a rework
touching just trace statements and doing only slight modifications.
The goal is to have identical printouts for the rc value (0x%08x),
mechanism (0x%lx), slot id (%ld), handles (%ld), key index (%ld).
Signed-off-by: Harald Freudenberger <freude@linux.vnet.ibm.com>
> Rework some trace strings

- testcases/ock_tests.sh.in
Apparently it was missing EP11.
> Ajust ock_tests to also work for EP11

- doc/README.ep11_stdll
- usr/lib/pkcs11/api/api_interface.c
- usr/lib/pkcs11/api/apiproto.h
- usr/lib/pkcs11/api/apiutil.c
- usr/lib/pkcs11/common/h_extern.h
- usr/lib/pkcs11/common/host_defs.h
- usr/lib/pkcs11/common/loadsave.c
- usr/lib/pkcs11/common/new_host.c
- usr/lib/pkcs11/common/obj_mgr.c
- usr/lib/pkcs11/common/tok_spec_struct.h
- usr/lib/pkcs11/common/tok_specific.h
- usr/lib/pkcs11/common/utility.c
- usr/lib/pkcs11/ep11_stdll/new_host.c
- usr/lib/pkcs11/icsf_stdll/icsf_specific.c
- usr/lib/pkcs11/icsf_stdll/new_host.c
- usr/lib/pkcs11/tpm_stdll/tpm_specific.c
- usr/sbin/pkcsslotd/slotmgr.c
The first patch ist just a update for the ep11 README document with an example configuration.
The second patch fix the access permission when creating new token directories.
The last 4 patches enable individual token locking instead having a single lock for all tokens. This is very useful when dealing with hundreds of tokens.
Developed by Ingo
> MTI additional patches

- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
- usr/lib/pkcs11/soft_stdll/soft_specific.c
We had moved from the deprecated _BSD_SOURCE to _DEFAULT_SOURCE, but some
distros are still running on older versions of glibc, so to avoid
incompatibility we check for the glibc and define the necessary source.
Also removed the _DEFAULT_SOURCE from EP11 code as it is not used anywhere.
> Fix glibc incompatibilty for the Soft Token

- usr/lib/pkcs11/common/host_defs.h
- usr/lib/pkcs11/common/loadsave.c
- usr/lib/pkcs11/common/new_host.c
- usr/lib/pkcs11/common/utility.c
- usr/lib/pkcs11/ep11_stdll/new_host.c
- usr/lib/pkcs11/icsf_stdll/icsf_specific.c
- usr/lib/pkcs11/icsf_stdll/new_host.c
- usr/sbin/pkcsslotd/Makefile.am
- usr/sbin/pkcsslotd/pkcsslotd.h
- usr/sbin/pkcsslotd/slotmgr.c
1. Fix migration problem due to incompatible size of shared memory objects.
Keep the old TOKEN_DATA structure to ensure shared memory objects has the same size
as  before. Additional data are moved the the token individual data storage.
2. Added some logic to check for duplicate token directories at slot daemon start.
Established hash table for token directories to check for redundancy.
> Amendments/Fixes for MTI

- configure.ac
- usr/lib/pkcs11/api/Makefile.am
- usr/lib/pkcs11/cca_stdll/Makefile.am
- usr/lib/pkcs11/common/lock_btree.c
- usr/lib/pkcs11/common/lock_sess_mgr.c
- usr/lib/pkcs11/common/new_host.c
- usr/lib/pkcs11/common/obj_mgr.c
- usr/lib/pkcs11/ep11_stdll/Makefile.am
- usr/lib/pkcs11/ep11_stdll/new_host.c
- usr/lib/pkcs11/ica_s390_stdll/Makefile.am
- usr/lib/pkcs11/icsf_stdll/Makefile.am
- usr/lib/pkcs11/icsf_stdll/new_host.c
- usr/lib/pkcs11/soft_stdll/Makefile.am
- usr/lib/pkcs11/tpm_stdll/Makefile.am
As an alternative solution to transactional memory, the user can specify during
build time if he wants to make use of read/write locks implementation. Just
include --enable-locks in configure step.
> Add locking mechanism as alternative to transactional memory

- usr/include/pkcs11/pkcs11types.h
- usr/lib/pkcs11/common/key.c
- usr/lib/pkcs11/common/p11util.c
- usr/lib/pkcs11/common/template.c
The PKCS#11 standard requires the CKA_ALWAYS_AUTHENTICATE attribute
to be present in private key objects. Actually this attribute is not
set as one of the default attributes. Further, it will be rejected
when it's declared within the application defined key template.
This fix will add the CKA_ALWAYS_AUTHENTICATE attribute by default
to any private key object. The value is set to 'false'. The calling
application is free to overrule by setting the attribute value
within the key template to 'true'.
Signed-off-by: Ingo Tuchscherer <ingo.tuchscherer@linux.vnet.ibm.com>
> Fix CKA_ALWAYS_AUTHENTICATE attribute for priv. keys

- usr/lib/pkcs11/common/lock_btree.c
- usr/lib/pkcs11/common/lock_sess_mgr.c
This changes were missing to make the implementation using locks to be able to
make use of MTI.
> Fix needed so locks can make use of MTI

- usr/sbin/pkcsconf/pkcsconf.c
> Fix error message when dlsym fails

- usr/lib/pkcs11/tpm_stdll/tpm_specific.c
After the implementation of the Multi Token Instances (MTI) some
of the function signatures have changed and old patches provided
by the distros were not reflected.
This patch removes the call of the function
object_mgr_purge_private_token_objects() from the
clear_internal_structures(), since it has being called by the TPM
functions that calls clear_internal_structures().
> Fix TPM data-structure reset function.

- .travis.yml
- configure.ac
Update checkings to build tokens. Now, CCA and Software tokens are enabled by default. The others, when checked the dependencies and requested to build, will be enabled.
Also, add new packages to be installed to enable token build by default. Now, with this configuration, the CCA, Software, ICSF and TPM tokens will be built by default.
> Fix configure and travis

- misc/Makefile.am
Add rule in Makefile to create the /usr/lib/tmpfiles.d directory
during the installation step.
> Make sure the creation of tmpfiles.d

- misc/Makefile.am
- misc/pkcsslotd.in
- rpm/opencryptoki.spec
- testcases/Makefile.am
- usr/sbin/pkcsslotd/shmem.c
Remove some pkcs11_startup leftovers
The old (previous version 3) pkcs11_startup configuration script was still being
called and mentioned in some of the code. Removed it to fix.
There is still mentioning of pkcs11_startup in some documents, those should be
maintained.
Remove tmpfiles.conf from install and fix doc names
During install the tmpfiles.conf is copied together with pkcsslotd.service into
the usr/lib/systemd/system/. But we already have tmpfiles.conf as
opencryptoki.conf in the correct folder usr/lib/tmpfiles.d/. So we can remove
it.
Also fixed some documents name in spec file.
> Fix pkcsconf for upstart (init.d) and fix spec file when building --with-systemd

- usr/lib/pkcs11/common/host_defs.h
- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
Introduce a field private_data in structure STDLL_TokData_t that allows
a token to anchor a pointer to a private control block to store all its
variables that are supposed to be global on a per token instance basis.
Instead of adding token specific fields for this purpose to the STDLL_TokData_t
structure (which is part of common code), the private_data field provides a
token implementation independent way of storing information on a per token
instance basis.
This patch also removes the EP11 specific field target_list from STDLL_TokData_t
into a EP11 specific private data block to keep STDLL_TokData_t free from any
token implementation specific fields.
> Token private data field in STDLL_TokData_t for multi-instance-token support

- usr/lib/pkcs11/common/mech_dsa.c
- usr/lib/pkcs11/ep11_stdll/Makefile.am
A tester reported a problem with the EP11 token when using the 3.8.1 release of OpenCryptoki. He got the following error when loading the EP11 token:
pkcsconf[55687]: apiutil.c DL_Load: dlopen() failed for [libpkcs11_ep11.so]; dlerror = [/usr/lib64/opencryptoki/stdll/libpkcs11_ep11.so: undefined symbol: dsa_sign]
This is caused by unresolved symbols in the EP11 token shared library.
> Fix problem with EP11 token loading

- usr/lib/pkcs11/api/Makefile.am
- usr/lib/pkcs11/cca_stdll/Makefile.am
- usr/lib/pkcs11/ep11_stdll/Makefile.am
- usr/lib/pkcs11/ica_s390_stdll/Makefile.am
- usr/lib/pkcs11/icsf_stdll/Makefile.am
- usr/lib/pkcs11/icsf_stdll/icsf.c
- usr/lib/pkcs11/soft_stdll/Makefile.am
- usr/lib/pkcs11/tpm_stdll/Makefile.am
While building the rpm some unresolved symbols issues came up.
To help on this we integrated #31 solution and fixed what was needed.
> Fix unresolved symbols

- usr/lib/pkcs11/common/trace.c
A recent change in commit ecf145ec74f3febf727ea1c2c590da2890e4ea4a
causes that no trace messages are written into the trace file.
This commit fixes the problem.
> Fix writing of trace messages

- man/man1/pkcsep11_migrate.1.in
This man page was lacking the necessity of setting the PKCS11_USER_PIN
environment variable before executing the pkcsep11_migrate tool.
> Update pkcsep11_migrate man page

- usr/include/pkcs11/pkcs11types.h
PKCS#11 v2.20 defines two macros (CK_TRUE and CK_FALSE) for use with
values of type CK_BBOOL. For backwards compatibility, we keep defining
TRUE and FALSE and CK_DISABLE_TRUE_VENDOR which may be set by the
application vendor.
Fix #23.
> Define CK_FALSE and CK_TRUE macros

- testcases/pkcs11/gen_purpose.c
The multi instance token support patch series also increased the
maximum number of tokens managed (NUMBER_SLOTS_MANAGED in slotmgr.h)
from 6 to 1024. The testcase gen_purpose passes a slot-id that
is supposed to be out of range to functions C_GetSlotInfo, C_GetTokenInfo,
C_GetMechanismList, and C_InitToken and expects CKR_SLOT_ID_INVALID
to be returned. With the increased number of managed slots, the
slot-id used by the testcase (i.e,. 999) is no longer out of range.
This commit changes the testcase to use slot-id 9999, so that it is
out of range again.
> Fix testcase after max number of slots managed was increased

- usr/lib/pkcs11/common/defs.h
While performing RSA OpenSSL speed test it was resulting on segmentation
fault when using ICA token for RSA key lengths bigger than 512. Increased the
MAX_RSA_KEYLEN to 1920 so we are able to perform RSA speed test
successfully.
Even though the SOFT token also uses the same MAX_RSA_KEYLEN parameter, we have a hack for SOFT token to fallback to OpenSSL, since the SOFT token by itself doesn't provide RSA algorithm implementation. That's why we only see this happening for ICA token.
> Increase RSA max key length

- usr/lib/pkcs11/common/utility.c
The check_user_and_group function checks for Root or effetive Root as
mentioned on the code comment, but the way that it is implemented it is
checking for Root AND effective Root, which is a totally different
logic.
Fix proposed by Red Hat.
> Fix check for user or effective user

- man/man1/Makefile.am
Some of the man pages should be built only if the token related to them were enabled during
compilation.
> Fix conditional man pages

- usr/lib/pkcs11/common/new_host.c
- usr/lib/pkcs11/ep11_stdll/new_host.c
- usr/lib/pkcs11/icsf_stdll/icsf_specific.c
- usr/lib/pkcs11/tpm_stdll/tpm_specific.c
During a token reinitialization, to set up a SO PIN or a User PIN again,
the operation would fail mentioning that the hash of the old PIN doesn't
match the entered old PIN. This happens because during InitToken
operation we are resetting the NV data, and with this we are loosing the
hash and md5 of the old PIN.
To fix this, instead of calling init_token_data on every InitToken, we
do a load_token_data, that will check if we have a NV data already
created. If yes, it just loads it. If not, it calls init_token_data.
> Fix token reinitialization

- usr/lib/pkcs11/api/api_interface.c
- usr/lib/pkcs11/common/new_host.c
- usr/lib/pkcs11/ep11_stdll/new_host.c
- usr/lib/pkcs11/icsf_stdll/new_host.c
The trace was showing session id 0 on tracing file for tokens that use
common/new_host.c, because we were not setting the handle of session
objects.
Also added better tracing when a session id is not valid.
> Fix tracing of session id

- testcases/misc_tests/obj_mgmt.c
- testcases/pkcs11/hw_fn.c
- usr/lib/pkcs11/common/hwf_obj.c
Monotonic Counters have read-only attributes. If during CreateObject the
supplied template specifies a value for any of the read-only attributes,
then the attempt should fail with the error code CKR_ATTRIBUTE_READ_ONLY.
Fixed tests that created Monotonic counters objects.
> Fix Hardware Feature Object validation and tests

- .gitignore
- testcases/pkcs11/gen_purpose.c
The Total and Ran number of tests executed was not matching the Passed
number of tests, which was Total+1.
>  Fix testcase result mismatch and update .gitignore

- usr/sbin/pkcsslotd/shmem.c
- usr/sbin/pkcsslotd/slotmgr.c
Removed a misleading pkcsslotd log message that was causing wrong
interpretations and also because it is not necessary. Created a new
informational log message to inform when PID file is created. This will
help in the future to know about systemd timing issues.
> Improve pkcsslotd logging

- testcases/pkcs11/copyobjects.c
- usr/lib/pkcs11/common/obj_mgr.c
- usr/lib/pkcs11/common/object.c
When some application call C_CopyObject and passes a null template and a
count of 0 then we should be able to continue and execute the copy, but
this was failing because of some wrong checks.
As a consequence I've also added a testcase to copyobjects to try to
copy an object when we pass a null template and check if the new object
matches the old object.
> Fix copy object when template is null

- usr/lib/pkcs11/ica_s390_stdll/ica_specific.c
- usr/lib/pkcs11/ica_s390_stdll/tok_struct.h
> ica_token: Fix compile problem with older libica without ECC support

- usr/lib/pkcs11/common/mech_sha.c
A wrong size during manual HMAC calculation causes that the
returned signature is wrong. This happens for the ICA token,
since it does not provide a token specific HMAC_Sign function.
Also remove an unnecessary second check for the token specific
HMAC-Sign function. This check is already done a few lines above and
is not needed again. If we reach there, there is no token specific
HMAC-Sign function.
> Fix a bug in sha512_hmac_sign()

- usr/lib/pkcs11/common/object.c
- usr/sbin/pkcscca/pkcscca.c
- usr/sbin/pkcscca/pkcscca.h
This fix was triggered by a customer problem. They reported problems when migrating the CCA token objects from OCK version 2 to version 3. The CCA migration tool pkcscca ended successfully, but AES keys stored in token objects were not usable afterwards.
> Fix CCA version migration tool

- testcases/common/common.c
- testcases/crypto/rsa_func.c
- usr/lib/pkcs11/common/sign_mgr.c
- usr/lib/pkcs11/common/verify_mgr.c
C_SignRecoverInit and C_VerifyRecoverInit must check for key attributes CKA_SIGN_RECOVER and CKA_VERIFY_RECOVER instead of CKA_SIGN and CKA_VERIFY being TRUE, otherwise the operations must fail with CKR_KEY_FUNCTION_NOT_PERMITTED.
> Correct Sign/VerifyRecover attribute checking

- usr/sbin/pkcsconf/pkcsconf.c
pkcsconf -m prints the backspace delete character ^ H to delete a trailing | when printing a mechanism's flag list:
This is working when printing to terminal, e.g.:
```
Mechanism #60
Mechanism: 0x2107 (CKM_AES_CFB128)
Key Size: 16-32
Flags: 0x60300 (CKF_ENCRYPT|CKF_DECRYPT|CKF_WRAP|CKF_UNWRAP)
```
When tool output is redirected to a file it looks like:
```
Mechanism #60
Mechanism: 0x2107 (CKM_AES_CFB128)
Key Size: 16-32
Flags: 0x60300 (CKF_ENCRYPT|CKF_DECRYPT|CKF_WRAP|CKF_UNWRAP|^H)
```
This PR has the fix.
> Dont print backspace delete ^ H in pkcsconf -m output

- usr/lib/pkcs11/cca_stdll/cca_specific.c
- usr/lib/pkcs11/common/attributes.c
- usr/lib/pkcs11/common/attributes.h
- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
The CCA and EP11 tokens uses secure keys. When importing a clear key the secure key blob is stored in attribute CKA_IBM_OPAQUE. The other attributes containing clear key material must be cleansed, but kept in their original length.
This fixes https://github.com/opencryptoki/opencryptoki/issues/153
Question: Should we really cleanse the public key parts also? The CCA token did so already for EC keys.....
> CCA/EP11: Cleanse clear key after importing keys 

- usr/lib/pkcs11/common/utility.c
compute_sha() leaks memory when using a token specific sha routine. The token specific sha init allocates a context, but leaves it to digest_mgr_cleanup() to free it. 
Usually the token specific sha routines are called by the digest manager, so digest manager also cares about freeing the context. Function compute_sha() does not use the digest manager, so it needs to free the context itself.
In general the token specific sha functions should free its context at end of token_specific_sha and token_specific_sha_final, but this is not how it is done in OCK. Also the token specific sign/verify and encrypt/decrypt routines do not free their contexts, but leave it to the sign/verify manager and the encrypt/decrypt manager to do so. So at least its consistent...
> Fix memory leak in compute_sha()

- usr/lib/pkcs11/cca_stdll/cca_specific.c
- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
- usr/lib/pkcs11/ica_s390_stdll/ica_specific.c
The CCA library does not like specifying a destination buffer
size > 512 bytes (4096 bits) for the signature target buffer
on RSA sign. This caused some testcases to fail as they specify
1024 bytes. Fixed by checking and rewriting the buffer size
parameter to be always <= 512 bytes.
Signed-off-by: Harald Freudenberger <freude@linux.ibm.com>
> CCA Token: Fix 8/72 failure on RSA sign destination buffer too big

- testcases/crypto/ec_func.c
- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
The EP11 library supports CKM_ECDH1_DERIVE slightly different than the PKCS#11 standard. It receives the public data directly as mechanism parameter. In PKCS#11, the mechanism parameter specifies struct CK_ECDH1_DERIVE_PARAMS which then contains the public data, a KDF and shared data.
Add code to accept CK_ECDH1_DERIVE_PARAMS as parameter, but pass the public data directly to EP11. KDFs other than CKD_NULL and shared data is still not supported and will return CKR_MECHANISM_PARAM_INVALID if specified.
Also update the EC testcase and remove special handling for EP11.
> EP11: Support CKM_ECDH1_DERIVE in PKCS#11 flavor 

- testcases/crypto/rsa_func.c
- testcases/crypto/rsaupdate_func.c
... just like the other testcases do already.
Makes it easier to understand which mechanism was skipped.
> Enhance SKIP message with human readable mechanism for RSA testcases

- testcases/crypto/rsa_func.c
- testcases/crypto/rsaupdate_func.c
Not all cases where a function has failed and testcase_error is called cause a stop of the test. This leads to follow on failures.
> TESTCASES: Stop the test after a testcase_error

- usr/lib/pkcs11/ep11_stdll/ep11_func.h
- usr/lib/pkcs11/ep11_stdll/ep11_specific.c
- usr/lib/pkcs11/ep11_stdll/ep11_specific.h
- usr/lib/pkcs11/ep11_stdll/new_host.c
Sometimes the EP11 token must adjust the behavior of the EP11 host library when its behavior is not exactly as defined by the PKCS#11 standard. This adjustments are mostly EP11 host library or even firmware version dependent. Also some new features are only available/working with a certain host library or firmware version.
This patch adds code to query the versions of the host library, the firmware API level and the firmware version, so that this version information can be used later on.
> EP11: add support for querying the EP11 lib and firmware version

- usr/lib/cca_stdll/cca_specific.c
- usr/lib/ica_s390_stdll/ica_specific.c
This fixes issue https://github.com/opencryptoki/opencryptoki/issues/186 for ICA and CCA. 
For EP11 the EP11 host library is providing the return codes, so we can't change this in OCK.
> ICA/CCA: Return CKR_CURVE_NOT_SUPPORTED when EC curve is not supported

- usr/lib/common/key_mgr.c
Local generated keys should have the CKA_LOCAL attribute
with a value of TRUE. However, this was not always the
case. Now the two functions key_mgr_generate_key() and
key_mgr_generate_key_pair() in key_mgr.c add this attribute
to the key template.
Signed-off-by: Harald Freudenberger <freude@linux.ibm.com>
> common: add CKA_LOCAL=TRUE attribute to local created keys

- usr/lib/ep11_stdll/ep11_func.h
> Fix -Wpedantic and a typo

- usr/lib/common/loadsave.c
- usr/lib/common/new_host.c
- usr/lib/common/obj_mgr.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/new_host.c
- usr/lib/tpm_stdll/tpm_specific.c
This fixes a problem with message `usr/lib/common/loadsave.c Cannot read size.` on syslog when running multi threaded.
Note: This patch is on top of the "Check XProcLock return values" patch.
Since that other patch is not yet merged, it is also included in this PR. 
I may need to rebase my patch once the other one is merged.
> Ensure the XProcLock is held when token object files are saved, read, or deleted.

- usr/lib/common/loadsave.c
The lock is released before the file is closed when saving the token data. This leaves a very small window where the file is not closed, but other processes may read the file. In this case the file may appear with a size of 0 bytes, thus loading the token data fails.
Fixes: https://github.com/opencryptoki/opencryptoki/issues/218
> Fix race condition with save_token_data/load_token_data()

- usr/sbin/pkcsep11_session/pkcsep11_session.c
When multiple VHSM-Session objects are left over to be logged out by the pkcsep11_session tool, it may happen that all or some of them contain the exact same session pin blob. Thus when logging out one of them, all others will receive CKR_SESSION_CLOSED when trying to log them out. This is not an error, since the session is already logged out in that case.
> pkcsep11_session: Allow already closed sessions

- usr/lib/common/obj_mgr.c
During C_FindObjectsInit() function object_mgr_update_from_shm() is called to synchronize the objects in the local btrees with the shared memory (SHM). Any objects that are only in the SHM (because other processes have added them in the meantime) are added to the local btrees, and any objects that are no longer in the SHM (because other processes have deleted them in the meantime) are removed from the local btrees.
This patch ensure that the objects are not only removed from the btrees (publ_token_obj_btree, priv_token_obj_btree), but also from the object-map (object_map_btree).
Leaving the removed object in the object-map causes that the left-over map entry points to a non-existing object. Later, when new objects are added, an object with the same btree-index may be created, and thus the …
> Ensure obj-map and obj-btrees are in sync when deleting objects

- usr/lib/ep11_stdll/ep11_specific.c
The target list is passed incorrectly to the handle_all_ep11_cards() function. Dependent on memory content, this can cause it to fail processing all EP11 cards. This will most likely cause a CKR_DEVICE_ERROR to be returned by C_Login when the STRICT_SESSION and/or VHSM_MODE is enabled in the ep11tok.conf config file.
> EP11: Fix target_list passing for EP11-session logon/logoff

- usr/lib/ep11_stdll/ep11_specific.c
EP11 does not allow to restrict a public RSA, EC, or DSA keys using CKA_VERIFY=FALSE or CKA_ENCRYPT=FALSE, because it can not be technically enforced since the public key material is available in clear (refer to chapter 2.2.6 of the EP11 structure document). Thus, generating a key pair using C_GenerateKeyPair fails with CKR_TEMPLATE_INCONSISTENT when the public key template contains CKA_VERIFY=FALSE or CKA_ENCRYPT=FALSE.
With this change, the EP11 token allows to restrict public keys with CKA_VERIFY=FALSE or CKA_ENCRYPT=FALSE. When specified, these attributes are overridden with TRUE when passing the key generate request to the EP11 library, but the original attribute values are stored in the object. The key usage restriction in regards of SIGN and ENCRYPT are enforced by the EP11 token, …
> EP11: Support key usage restrictions for public keys

- usr/lib/api/apiutil.c
- usr/sbin/pkcsslotd/mutex.c
A stat() before open() is not required and can cause timing ralted errors. The code can directly react on the result of open(). Flag O_CREAT will create the file only if it is not existent, so we don't need to know upfront if the file exists already or not.
**For discussion:** 
The only difference in usr/sbin/pkcsslotd/mutex.c is that now the code always uses fchmod() and fchown() on the lock file when the lock file was successfully opened, so also when it was already existent, not only when it was newly created. This happens once when pkcsslotd starts, so IMHO this does not hurt.
> Fix coverty scan findings for stat/open

- testcases/crypto/rsa.h
- testcases/crypto/rsa_func.c
- usr/lib/ep11_stdll/ep11_specific.c
The EP11 host library does not allow to use plain SPKIs as public key blobs for encrypt operations, this requires MACed-SPKIs. Create MACed-SPKIs whenever public keys are imported, and store it in CKA_IBM_OPAQUE instead of the plain SPKI.
> EP11: Created MACed-SPKIs when importing public keys

- usr/lib/soft_stdll/soft_specific.c
Multipart signing calling C_SignFinal the first time with a NULL
signature will cause a segfault.
Closes: https://github.com/opencryptoki/opencryptoki/pull/237
Signed-off-by: Hugo Géroux <hugo.geroux@gmail.com>
> SOFT: C_SignFinal with NULL signature causes segfault

- usr/lib/common/loadsave.c
Opencryptoki allows that a token uses a per-user data store. That is, the token directory then contains the user name, e.g. `/var/lib/opencryptoki/tpm/root`. Currently only the TPM token makes use of this, all other tokens share the data store across all, users.
Support for per-user data store got lost with commit 'MTI [PATCH 04/85]: Initialize token' https://github.com/opencryptoki/opencryptoki/commit/39a7685295a7fe3688dd66cbed687deefe06bee6.
Fixes: https://github.com/opencryptoki/opencryptoki/issues/242
**Note:** I can't test this with the TPM token, since I don't have a setup for testing the TPM token, but I simulated the per-user data store using the ICA token. Would be nice if someone with a TPM setup could test this....
> Fix per-user data store option

- usr/sbin/pkcsslotd/lexer.l
opencryptoki-3.12.0 cannot be built on rhel-7, it breaks with the following error:
---
usr/sbin/pkcsslotd/lexer.l: In function 'yylex':
usr/sbin/pkcsslotd/lexer.l:60:20: error: 'uint32_t' undeclared (first use in this function)
yylval.num = (uint32_t)major << 16 | (uint32_t)minor;
---
this type is defined in the C header <stdint.h>, adding include <stdint.h> into lexer.l resolves this issue.
I have opened a pull request for this.
> error: 'uint32_t' undeclared

- usr/sbin/pkcsep11_migrate/ep11adm.h
- usr/sbin/pkcsep11_migrate/pkcsep11_migrate.c
Since commit 2668e8f347ca2514b4274daccf71defce0e2313f the contents of attribute CKA_IBM_OPAQUE has been changed to contain the raw EP11 blob directly, no longer wrapped into struct ep11_opaque.
Since then, the pkcsep11_migrate tool could not have worked to re-encrypt EP11 key blobs stored in token objects.
Correct the tool and while at it also replace some older, now deprecated EP11 host library functions with ist newer equivalents.
> Fix the pkcsep11_migrate tool

- testcases/crypto/aes_func.c
The AES Wrap/Unwrap testcase uses mechanism CKM_RSA_PKCS to test if an unwrapped RSA key can be used for en/decryption. This fails if mechanism CKM_RSA_PKCS is not available (e.g. due to control point settings). Skip the whole testcase if CKM_RSA_PKCS is not available.
> TESTCASES: Skip test if CKM_RSA_PKCS is not available

- usr/lib/ep11_stdll/ep11_specific.c
Function ec_uncompress_public_key() expects the size of the output buffer in out_pubkey to be specified in the out_len parameter. However, variable pubkey_len is uninitialized when calling
ec_uncompress_public_key(), so this may result in CKR_BUFFER_TOO_SMALL dependent on the value of pubkey_len. Fix this by setting pubkey_len to the size of the public key buffer allocated above.
> EP11: Fix EC-uncompress buffer length

- usr/lib/ep11_stdll/ep11_specific.c
- usr/sbin/pkcsep11_migrate/pkcsep11_migrate.c
- usr/sbin/pkcsep11_session/pkcsep11_session.c
To allow running with the EP11 HSM simulation, any sysfs related places in the code need to be changed to return configured values. Also load the EP11 host library with dlopen option RTLD_DEEPBIND to avoid a symbol name clash with the CCA host library.
To enable HSM simulation, configure with the following options: 'CFLAGS=-DEP11_HSMSIM -DEP11_HSMSIM_CARD_TYPE=7'
Symbol EP11_HSMSIM enables HSM simulation, EP11_HSMSIM_CARD_TYPE specifies the card type to simulate (e.g. 7 means it simulates a CEX7P card).
Use environment variable OCK_EP11_LIBRARY to specify the name and path of the EP11 Host Library for the simulation.
> EP11: Add support for EP11 HSM simulation

- usr/lib/ep11_stdll/ep11_specific.c
template_attribute_find returns true or false, which was
not handled correctly here.
> Fix return code checking when using template_attribute_find

- usr/sbin/pkcsslotd/mutex.c
DestroyMutexes() in sbin/pkcsslotd/mutex.c was actually a NOP. It just acquired the lock and released it right away, but it did not destroy the file lock.
> Minor cleanup

- usr/lib/common/key.c
- usr/lib/ep11_stdll/ep11_specific.c
The IBM implementation uses the "rho" value as the common attribute
between public and private key.
> EP11: Dilithium stage1, rename public key attribute "seed" to "rho"

- usr/lib/soft_stdll/soft_specific.c
The U64 macro seems to be removed from public header file.
edit: There are still warnings regarding the next openssl release's function deprecations but for now i only want a working build.
> Fix build with openssl master

- configure.ac
Tested all combinations of:
```
./configure
./configure --enable-locks
./configure --enable-locks=no
./configure --disable-locks
```
Normally, the opposite of default is listed in the `./configure --help` output (i.e. `--disable` for things that are enabled by default), and this variable seems important enough to show, given that default has recently changed.
Also note that prior to v3.13 the locks flag behavior was buggy, and `--disable-locks` actually enabled using locks, instead of transactional memory.
> configure.ac: add locks status message, and improve configure --help

- .travis.yml
- usr/include/slotmgr.h
- usr/lib/cca_stdll/cca_specific.c
- usr/lib/common/utility.c
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ica_s390_stdll/ica_specific.c
- usr/lib/icsf_stdll/icsf_specific.c
- usr/lib/soft_stdll/soft_specific.c
- usr/lib/tpm_stdll/tpm_specific.c
- usr/sbin/pkcsconf/pkcsconf.c
See only the last 2 commits (on top of ingo's PR).
- unify library,slot and token info
- use 0 or empty values for fields that have no meaning, instead of using dummy values
- update travis.yml
> Set sane defaults for library,slot and token information

- usr/include/local_types.h
- usr/lib/common/lock_btree.c
Function bt_put_node_value() does not really modify the btree, but it decrements the node values reference count.
Do not use the btree's mutex to lock the reference count from being modified concurrently, but use the built-in functions for atomic memory access instead. This allows bt_put_node_value() to run lock-free.
That way, we can save one mutex-lock/unlock cycle per typical BTree access (bt_get_node_value()/bt_put_node_value()).
> Avoid mutex lock at bt_put_node_value()

- usr/lib/api/api_interface.c
When `C_Initialize` errors prior to the `bt_init` call, `bt_destroy` will be
called on garbage memory because `Anchor` hasn't yet been zeroed. This
gives a stack trace such as:
Stack trace of thread 27740:
#0  0x00007fce91552b05 raise (libc.so.6 + 0x3cb05)
#1  0x00007fce9153b8a4 abort (libc.so.6 + 0x258a4)
#2  0x00007fce908db2e1 _ZN2os5abortEb.cold (libjvm.so + 0x20f2e1)
#3  0x00007fce911f76c2 _ZN7VMError14report_and_dieEv (libjvm.so + 0xb2b6c2)
#4  0x00007fce90fe7a24 JVM_handle_linux_signal (libjvm.so + 0x91ba24)
#5  0x00007fce90fdaa9c _Z13signalHandleriP9siginfo_tPv (libjvm.so + 0x90ea9c)
#6  0x00007fce91552b90 __restore_rt (libc.so.6 + 0x3cb90)
#7  0x00007fce7a262550 bt_destroy (libopencryptoki.so + 0x11550)
#8  0x00007fce7a2600d6 C_Initialize (libopencryptoki.so + 0xf0d6)
#9 …
> Handle early error cases in C_Initialize

- usr/lib/common/loadsave.c
- usr/sbin/pkcstok_migrate/pkcstok_migrate.c
- usr/sbin/pkcstok_migrate/pkcstok_migrate.mk
The new format stores all numeric fields in big endian, while the old format uses the platform endianness. So convert the fields to big endian during conversion.
@p-steuer: As discussed, please test this on x86 Linux, thanks.
> pkcstok_migrate: Fix NVTOK.DAT conversion on little endian platforms

- usr/include/slotmgr.h
- usr/lib/common/h_extern.h
- usr/lib/common/loadsave.c
- usr/lib/common/new_host.c
- usr/lib/common/p11util.c
- usr/lib/common/utility.c
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/icsf_specific.c
- usr/lib/icsf_stdll/new_host.c
- usr/lib/tpm_stdll/tpm_openssl.c
- usr/lib/tpm_stdll/tpm_specific.c
- usr/sbin/p11sak/p11sak.c
- usr/sbin/pkcsep11_migrate/pkcsep11_migrate.c
- usr/sbin/pkcsep11_session/pkcsep11_session.c
- usr/sbin/pkcsslotd/log.c
- usr/sbin/pkcsslotd/shmem.c
- usr/sbin/pkcsslotd/slotmgr.c
- usr/sbin/pkcstok_migrate/pkcstok_migrate.c
Don't use environment variables in all cases.  If running under setuid, we
should not trust the environment without additional sanitization.  Especially
for loading libraries, we cannot use input from untrusted environment
variables.
Some paths were written under some assumptions that paths never overflow.
Instead, we use a checked path creation.  If the path name overflows, the
function that tries to use the path name fails.
This commit only includes reworks on getenv and sprintf.  Further functions
should still be checked.
There are also some minor cosmetic fixes:
- Don't calloc if we anyway write all allocated bytes directly afterwards.
- Don't allocate paths larger than PATH_MAX.
> Fixes for potential vulnerabilities

- testcases/common/common.c
- testcases/include/regress.h
- usr/sbin/pkcstok_migrate/pkcstok_migrate.c
GCC 10 complains about a snprintf.  The real problem is the strcat in the next
line.  However, the lines can easily be simplified to also remove the warning.
> Fix GCC 10 compiler warning in pkcstok_migrate.c

- usr/lib/common/parser.y
There were too many rules that allowed multiple successive lines of comments
or newlines.  This caused two shift/reduce conflicts in the parser.  By simply
eliminating the main rule we get a grammar that still recognizes the same
language as the previous one.  But this one does not have any shift/reduce
conflicts.
> Remove superfluous parser rule

- Makefile.am
The uninstall targets leaves ep11tok.conf and ep11cpfilter.conf in the
configuration directories.  Remove these two to have a clean uninstall.
> Remove ep11 configuration on uninstall

- Makefile.am
When running tests via "make installcheck" with "PKCS11_TEST_USER", that user
must be granted write access to the testcases folder since it will generate
the log-files in this folder.  Without this, ock_test.sh will not be able to
run successfully.
> Make testcases-folder world writable for su tests

- Makefile.am
This target is supposed to contain all checks that should only run in the CI
but not on a "make installcheck".  Examples include token pin changes and
master key changes.
> Add ci-installcheck make target

- testcases/ock_tests.sh.in
Add some of the tests in testcases/pkcs11/ and testcases/misc_tests/ to be executed in ock_tests.sh. This will execute these testcases also in Travis CI for the soft token, as well as other CIs that run 'make ci-installcheck' or 'make installcheck'.
> Add more tests to be executed in ock_tests.sh

- configure.ac
- testcases/README
- testcases/build/build.mk
- testcases/build/cpp_test.cpp
- testcases/testcases.mk
Regression test for https://github.com/opencryptoki/opencryptoki/pull/350 . Travis is expected to fail until 350 is merged.
> Add C++ build test

- testcases/build/cpp_test.cpp
pkcs11.h just includes other openCryptoki headers from
system locations.
> Fix cpp_test

- usr/lib/common/template.c
- usr/lib/ep11_stdll/new_host.c
Just two small fixes:
- The wrong comment in template_update_attribute was obvious, but Ingo also suggested to change the return code from "function failed" to arguments bad", because this fits better.
- The malloc() in the four init functions for encr/decr/sign/verify caused a problem in aes_cmac_sign where the mac_len is calculated, because malloc(0) returned some undefined value, which got assigned to mech.pParameter. Therefore let's do the malloc only if a mech param is given.
> Bugfix and comment

- usr/lib/common/pkcs_utils.c
- usr/sbin/pkcscca/pkcscca.c
- usr/sbin/pkcscca/pkcscca.h
- usr/sbin/pkcscca/pkcscca.mk
This is an attempt to remove the duplicated code parts that have been copied from common code files into pkcscca.c. Duplicating code causes a maintenance nightmare.
Instead of duplicating the code, link the common code parts into pkcscca. Unfortunately, almost all common code parts  need tobe included, to resolve all referenced symbols. That way lots of unused code is included into pkcscca, but at least its the exact same code as for the tokens.
Take a look and let me know what you think. If you prefer to keep the code duplication, thats fine with me, too.....
> PKCSCCA: Remove duplicated common code

- testcases/common/common.c
- testcases/misc_tests/cca_export_import_test.c
- testcases/misc_tests/misc_tests.mk
- usr/lib/cca_stdll/cca_specific.c
- usr/lib/cca_stdll/cca_stdll.h
- usr/lib/common/attributes.c
- usr/lib/common/attributes.h
- usr/lib/common/h_extern.h
- usr/lib/common/key.c
- usr/lib/common/new_host.c
- usr/lib/common/p11util.c
- usr/lib/common/p11util.h
- usr/lib/common/template.c
- usr/lib/common/trace.c
- usr/lib/common/trace.h
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/new_host.c
3 commits:
- TESTCASES: new testcase to test CCA opaque key token export and import
- CCA: support import of raw cca tokens with C_ObjectCreate via CKA_IBM_OPAQUE
- CCA: store only public token in IBM_OPAQUE attribute
for more details pleas see header of each commit
> Support import of raw cca tokens with C_ObjectCreate

- usr/lib/cca_stdll/tok_struct.h
- usr/lib/common/object.c
- usr/lib/common/tok_spec_struct.h
- usr/lib/common/tok_specific.h
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ep11_stdll/tok_struct.h
- usr/lib/ica_s390_stdll/tok_struct.h
- usr/lib/icsf_stdll/tok_struct.h
- usr/lib/soft_stdll/tok_struct.h
- usr/lib/tpm_stdll/tok_struct.h
The EP11 key blob also contains a set of attributes (e.g. boolean attributes). Make sure that when attributes are changed (e.g. via C_SetAttributeValues), that the key blob is also updated with the changed attributes. Otherwise the view of the attributes of a key as seen by OCK and the view of the attributes as seen by EP11 may differ. This may cause errors (e.g. rejects of certain operations)  due to different attributes.
> EP11: Update attributes in key blob when attributes are changed

- usr/sbin/p11sak/p11sak.c
Fixes bug in delete-key command when CTRL+D is user input. 
Added comment that key with a certain label was not found and deleted if it was not found.
Signed-off-by: matthias.reumann1@ibm.com
> Bug Fix and added Error handling

- testcases/crypto/digest_func.c
- testcases/crypto/ec_func.c
- testcases/crypto/rsaupdate_func.c
- usr/lib/common/key.c
- usr/lib/common/sign_mgr.c
- usr/lib/common/template.c
- usr/lib/common/verify_mgr.c
The following attributes can not be modified after object creation:
CKA_ALLOWED_MECHANISMS, CKA_WRAP_TEMPLATE, CKA_UNWRAP_TEMPLATE, and
CKA_ALWAYS_AUTHENTICATE. Return CKR_ATTRIBUTE_READ_ONLY if those
attributes are being modified.
> Fix: Some attributes can not be modified after object creation

- Makefile.am
- testcases/misc_tests/p11sak_test.sh
- usr/sbin/p11sak/p11sak.c
Fixed off-by-one write to heap, testcase and test case executor.
> Fixed p11sak and corresponding test case

- testcases/crypto/ec_func.c
- usr/lib/ep11_stdll/ep11_specific.c
These are two fixes for pre-z15 processors. One is an old, known problem, the other one is a bug in a newly added testcase for protected key support.
> Two bug fixes in testcases

- usr/sbin/p11sak/p11sak.c
A few fixes on attribute handling in p11sak:
- The token attr (T) is always true and ignored when specified for keygen
- All attrs are only applicable for symmetric keys, a subset is applicable for asymmetric keys. This is now reflected in the key type specific help
- Msg "Unknown argument '%c'" is replaced by a more "speaking" msg
> p11sak: fix attributes help

- testcases/misc_tests/obj_lock.c
- usr/lib/common/h_extern.h
- usr/lib/common/mech_ec.c
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ica_s390_stdll/ica_specific.c
- usr/lib/soft_stdll/soft_specific.c
The previous commit did not completely fix the detection of the ECDH public data format.
When a raw ECPoint starts with 0x04 followed by a byte who's value is 2 less than the length of the public data, followed by a byte that is a valid point conversion indicator (e.g. 0x02 - compressed, 0x04 - uncompressed, or 0x06 - hybrid) then it would have still been detected as an DER encoded EC Point, resulting in a wrong EC Point.
The detection logic is corrected and is now moved into a separate function, and is used at all 3 places, i.e. in th soft token, the ICA token, and the EP11 token.
> Fix detection of DER encoded or raw ECDH public data (2)

- usr/lib/common/common.mk
Missing dependency caused build errors in some parallel builds.
> COMMON: Add dependency between lexer and parser.

- usr/lib/common/decr_mgr.c
- usr/lib/common/encr_mgr.c
- usr/lib/common/mech_rsa.c
- usr/lib/common/sign_mgr.c
- usr/lib/ep11_stdll/ep11_specific.c
Do not get and read-lock an object twice within the same thread via function object_mgr_find_in_map1(), as this would read-lock the object twice.
This could cause a deadlock situation, when in-between the first and the second call to object_mgr_find_in_map1() the token object is modified by another process. The second object_mgr_find_in_map1() would detect that the object has been modified (object_mgr_check_shm()), and would try to re-load the object from the disk. For re-loading, the object is unlocked once, and a write-lock is acquired instead. However, if the current thread has read-locked the object twice, but releases only one read-lock, then it will never get the write lock, because it still owns the read lock itself.
To avoid this situation, release the read-lock before calling …
> Fix potential deadlock situation with double read-locks

- usr/lib/soft_stdll/soft_specific.c
When constructing an OpenSSL EC public or private key from PKCS#11 attributes or ECDH public data, check that the key is valid, i.e. that the point is on the curve.
This prevents one from creating an EC key object via C_CreateObject with invalid key data. It also prevents C_DeriveKey to derive a secret using ECDH with an EC public key (public data) that uses a different curve
or is invalid by other means.
> SOFT: Check the EC Key on C_CreateObject and C_DeriveKey

- usr/lib/ep11_stdll/ep11_specific.c
Add a version check to filter out mechanism CKM_RSA_PKCS_OAEP when running with crypto cards < CEX6. Support for CKM_RSA_PKCS_OAEP is available only since CEX6 with firmware version 6.7.
This fixes some testcase failures in the CI when running on systems with mixed crypto card levels, including a CEX5 card.
> EP11: CKM_RSA_PKCS_OAEP is only supported since CEX6

- usr/sbin/pkcsslotd/slotmgr.c
Parser rework introduced a bug in the multitenant setup.
Rework of the CI to cover this feature will be postponed due to missing time.
> [COMMON] Fix multitenant setup

- testcases/crypto/ec_func.c
- usr/lib/ica_s390_stdll/ica_specific.c
This pr fixes issue #404. 
When libica has no crypto cards, the set of supported EC curves depends on openssl.
If openssl is e.g. in FIPS mode, very few curves are supported. This was not handled
correctly in icatoken and the EC tests. 
As libica itself does not provide sign update, I added the check for unsupported curves
only for sign and sign final to keep changes small. We may discuss this.
> ICA: handle unsupported curves correctly for openssl fallbacks

- usr/lib/ica_s390_stdll/ica_specific.c
With commit "Fix checking if curve supported in key generate, init, derive",
libica returns EPERM, if a key is generated, initialized, or derived, and
the EC curve is not supported.
> ICA: Fix libica return code handling for unsupported curves

- Makefile.am
- testcases/ciconfig.sh
- testcases/init_vhsm.exp.in
- testcases/misc_tests/p11sak_test.sh
- testcases/ock_tests.sh.in
- testcases/testcases.mk
Change our CI code such that we test more paths.  For every token we now test
multi tenant support by instantiating at least two tokens.  New token naming
scheme for the CI is:
Token numbers: <typenum><count>
where <typename> is
ICA:  1
CCA:  2
SW:   3
EP11: 4
For all except EP11 we have as tokname the lowercase type followed by a
0-based count (similar to token numbers).  For EP11 the token is called "ep"
followed by the 0-based count.  Furthermore, for EP11 the token configuration
file differs between the tokens:
0: Default with only APQN_ANY
1: FORCE_SENSITIVE and APQN_ANY
2: STRICT_MODE, VHSM_MODE, and APQN_ANY
3: OPTIMIZE_SINGLE_OPERATIONS and APQN_ANY
4: DIGEST_LIBICA OFF and APQN_ANY
5: PKEY_MODE DISABLED and APQN_ANY
6: AQPN_WHITELIST selecting the latest CEXP as defined in …
> Improve CI coverage

- Makefile.am
- testcases/ciconfig.sh
- testcases/init_token.sh.in
With the addition of lots of slots to our CI the initialization of slots ran
into timeouts in the expect scripts.  Unfortunately these errors were ignored
(expect standard action) which caused uninitialized slots to be tested.
Remove the 5 second timeout in preference of the default 10 seconds and treat
timeout errors in the expect script.
Also provide a cleanup target for the CI that correctly removes all token data
such that the next run starts from a clean state.
Do not attempt to reinitialize slot 42 if it is already initialized.
Switch slot 45 to use PKEYs since the default and disabled setting currently
cover the same code paths.
> [TEST] Fix setup and cleanup of slots

- Makefile.am
- testcases/init_token.sh.in
- testcases/init_vhsm.exp.in
Initializing 12 tokens in parallel causes some random bugs in our CI.  To
prevent these, initialize the tokens in sequence such that in the log output
the errors and commands can be identified without interleaving of other
commands and stray newline characters.
> Serialize token initialization

- usr/sbin/pkcstok_migrate/pkcstok_migrate.c
When modifying opencryptoki.conf during token migration, put quotes around strings that contain spaces, e.g. for the slot description and manufacturer.
> pkcstok_migrate: Quote strings with spaces in opencryptoki.conf

- configure.ac
AC_PROG_CXX will return "g++" even if no c++ compiler is installed, but does not fail. Add a check to detect if the C++ compiler is missing and fail the configure script if so.
> configure: Add check for C++ compiler

- testcases/ock_tests.sh.in
Introduce an environment variable OCK_TRACE_TOKENS to specify which slots
should be traced.  Set this environment variable to a space-separated list of
token numbers and the ock_test.sh driver will set OPENCRYPTOKI_TRACE_LEVEL to
4 before running tests on these slots.
> [TEST] Allow to specify which slot should be traced.

- usr/sbin/pkcstok_migrate/pkcstok_migrate.c
When migrating a slot the opencryptoki.conf file is modified. If it contains slots that already contain the 'tokversion = x.y' keyword, this is accidentally removed when migrating another slot.
> pkcstok_migrate: Don't remove 'tokversion = x.y' during migration

- usr/lib/common/shared_memory.c
- usr/lib/common/utility.c
- usr/lib/icsf_stdll/icsf_specific.c
The shm token segments were generated with permission 0666 for the user that
created the segment and the corresponding primary group.  This is potentially
a security problem since especially the segmant was word-rw.
This patch changes the permission to 0660 and changes the ownership of the
segment on creation to group "pkcs11".  Since every user that should be
allowed to use OCK has to be in that group, we should not have any usage
regressions.  If the segments already exist, a reboot might be necessary (or
any other way that cleans up the segments).
> [COMMON,ICSF] Fix permission of token SHM segment.

- Makefile.am
- testcases/cleanup_vhsm.exp.in
- testcases/init_token.sh.in
- testcases/init_vhsm.exp.in
- testcases/testcases.mk
Allow to cleanup left over EP11 sessions for CI runs via 'make ci-cleanup'. This is to be called by the CI after 'make ci-installcheck', and before pkcsslotd is terminated.
> CI: Perform cleanup of left over EP11 sessions

- usr/lib/common/shared_memory.c
usr/lib/common/shared_memory.c:229:9: warning: implicit declaration of function
‘OCK_SYSLOG’; did you mean ‘LOG_SYSLOG’? [-Wimplicit-function-declaration]
229 |         OCK_SYSLOG(LOG_ERR,
|         ^~~~~~~~~~
/usr/bin/ld:
usr/lib/common/sbin_pkcscca_pkcscca-shared_memory.o: in function `sm_open':
undefined reference to `OCK_SYSLOG'
collect2: error: ld returned 1 exit status
> Fix compile error

- Makefile.am
Target ci-installcheck stopped the pkcsslotd, so restart it before running cleanup_vhsm.exp and stop it afterwards.
> CI: Fix ci-cleanup target

- .travis.yml
We require OpenSSL >= 1.1.1 now.
> Update travis from Ubuntu 18.04 LTS to Ubuntu 20.04 LTS

- testcases/crypto/dsa_func.c
Leaving token object hanging around after the testcase may cause trouble with testcases executed afterwards, e.g. the obj_mgmt_tests does not expect to find any other token objects except those it created itself. 
FYI: @chrisRund
> TESTCASE: DSA: Destroy objects created during testing

- testcases/common/common.c
- testcases/crypto/ec_func.c
The CEX5P seems to have a firmware bug that hinders it from deriving a valid EP11 key blob for a derived key size <= 8. Enhance the testcases to identify situations where invalid/unusable key blobs are produced, but also skip tests the derive keys <= 8 bytes for the EP11 token until the firmware bug is resolved.
Note: For EP11, the smallest really usable CKK_GENERIC_SECRET key is 10 bytes anyway. AES or DES/3DES keys are larger. Keys of type CKK_GENERIC_SECRET can be used for HMAC mechanism only, and HMAC usually requires a minimum key size of digest-size / 2. For HMAC-SHA-1 the minimum key is therefore 20 / 2 = 10 bytes. This key size restriction an be lifted via control point XCP_CPB_KEYSZ_HMAC_ANY for EP11.
> Testcases: EP11 can't derive keys <= 8 bytes on a CEX5

- usr/lib/soft_stdll/soft_specific.c
OpenSSL 3.0 behaves different in reporting an error when an unsupported EC curve is used to generate an EC key. OpenSSL 1.1.1 returns an error at EVP_PKEY_CTX_set_ec_paramgen_curve_nid() already, but OpenSSL 3.0 returns
an error only at EVP_PKEY_keygen().
> SOFT: Detect unsupported EC curves with OpenSSL 3.0

- testcases/ciconfig.sh
Unfortunately the %y in the date format was meant to be a %j to have the day
in the year.
Also added a log output to see which token format we are using.
> [CI] Fix token store usage in CI

- usr/lib/config/cfgparse.y
- usr/lib/config/config.mk
- usr/lib/config/configuration.c
- usr/lib/config/configuration.h
The inital configlib commit did not include the possibility to use bare word
constants.  This is needed, e.g., for the "disable-event-support" keyword of
opencryptoki.conf.
To support this, add ConfigNodeBareConst to keep the constant in the key
without any further values in the node.  Also restructure the grammar:
- Every configelem now takes care of the positions of comments _within_ and
_after_ the element.
- Since "after element i" is "before element (i+1)", the config element cannot
take care of comments before the element (shift/reduce conflict since the
parser cannot know if the comment is after element i or before element i+1).
To alleviate this situation and preserve comments at the beginning of a file
or a structure content, add a commentedconfigelemstar that only takes care of …
> Config: Add BARE constants and some bugfixes

- testcases/crypto/aes_func.c
- usr/include/apictl.h
- usr/lib/api/api_interface.c
- usr/lib/common/mech_md5.c
- usr/lib/common/mech_sha.c
- usr/lib/ica_s390_stdll/ica_specific.c
- usr/lib/soft_stdll/soft_specific.c
libica may support RSA keys > 1024 only if running in FIPS mode. Make sure the ICA token adjusts its mon/max key sizes accordingly.
Also make sure testcases only use RSA key sizes supported by the token.
> ICA: Adjust min/max key sizes for RSA mechanisms according to libica's support

- usr/lib/api/api_interface.c
- usr/lib/api/apiutil.c
- usr/sbin/pkcsconf/pkcsconf.c
- usr/sbin/pkcsslotd/slotmgr.c
C_GetSlotList with tokenPresent=false is supposed to list all configured slots, not only those with a token present.  Also let 'pkcsconf -t' and 'pkcsconf -l' list all configured slots, not only those with a token present
> List all configured slots with C_GetSlotList and 'pkcsconf -t'

- usr/lib/common/mech_ec.c
- usr/lib/ep11_stdll/ep11_specific.c
For whatever reason, CKM_GENERIC_SECRET_KEY_GEN was excluded from the list of supported mechanisms of the EP11 token.
> EP11: Add support for CKM_GENERIC_SECRET_KEY_GEN

- testcases/unit/configdump.c
- testcases/unit/unit.mk
- usr/lib/config/configuration.c
Configlib dump did not correctly dump bare lists and indented elements that were not separated by newlines.  Added some unit tests to cover these scenarios.
Since this branch needs the unit test directory which is added by the Policy PR, it currently includes all Policy PR commits.  Only the last two commits are actually new.
> Configlib: Bugfix for dump and some tests

- usr/lib/api/policy.c
This was forgotten in the signature size determination code and cause failures
during the CI run on EP11.
> API: Add CKM_IBM_ED25519_SHA512 to policy

- testcases/misc_tests/tok2tok_transport.c
The same that was fixed with commit 022f04d9902d2d621158f1acefc0c7268b95ed6b for EC keys can also happen with RSA keys. Lets skip the testcase for RSA keys the same way as for EC keys.
FYI: @chrisRund
> TESTCASE: tok2tok_transport: Enhance error handling

- usr/lib/api/api_interface.c
Closes: https://github.com/opencryptoki/opencryptoki/issues/493
> API: Unlock GlobMutex if user and group check fails

- usr/lib/common/key.c
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ica_s390_stdll/ica_specific.c
Now that libica version 4 is available, we need to adjust the ICA and EP11 tokens to support libica version 4 (libica.so.4), but fallback to version 3 (libica.so.3) if version 4 is not available. That way we don't have a requirement on a specific libica version.
> libica version 4 support and a minor fix

- man/man7/opencryptoki.7.in
The note about arbitrary code execution is no longer true since commit 3686bd27f890e95f47bc23d4961a1de4d87013da from 2013. This commit was included since Opencryptoki version 3.0.
Before that commit, the location of some shared libraries to be loaded were stored in the shared memory segment. Users in the pkcs11 group could write to the shared memory and thus replace those paths by their own shared libraries, which enabled arbitrary code execution e.g., by placing malicious code it in the library constructor.
Since the above commit, the location of those shared libraries is not read from the shared memory segment anymore since that was replaced by socket communication.
This fixes https://github.com/opencryptoki/opencryptoki/issues/467
> MAN: Update security note in opencryptoki man page

- man/man1/p11sak.1.in
- usr/sbin/p11sak/p11sak.c
This is a small fix addressing a problem, where p11sak sets the CKA_PRIVATE attribute for every generated key to true. CKA_PRIVATE can now be set, alongside the other standard attributes, with the --attr option and the letter P.
> P11SAK: CKA_PRIVATE now set by OCK

- usr/lib/ica_s390_stdll/ica_specific.c
Return an error if we can't obtain the lock for the ICA RNG.
> ICA: Check fur successful pthread_mutex_lock()

- man/man1/p11sak.1.in
- usr/sbin/p11sak/p11sak.c
It is now possible to set different attributes for the public and private key while generating a new asymmetric key. It is explained in detail in the p11sak manpage.
> P11SAK: different attr sets for pub and prv key

- usr/sbin/p11sak/p11sak.c
Print a user friendly error message in case of policy rejections.
Policy rejections are indicated by CKR_FUNCTION_FAILED together with
field ulDeviceError in CK_SESSION_INFO being CKR_POLICY_VIOLATION.
> p11sak: User friendly error in case of policy rejections

- usr/sbin/p11sak/p11sak.c
Before attempting to generate a key using a mechanism, check if that mechanism is supported by the token in the selected slot, and if the key size is supported. Display a user friendly error message if not.
Closes: https://github.com/opencryptoki/opencryptoki/issues/485
> p11sak: User friendly error when mechanism or key size is not supported

- misc/pkcsslotd.in
- misc/pkcsslotd.service.in
- usr/include/slotmgr.h
The usage of /var/run is deprecated.
Change was suggested by Mark Post (@markkp) in https://github.com/opencryptoki/opencryptoki/pull/403
> Change /var/run to /run for pid file and sockets

- usr/lib/icsf_stdll/pbkdf.c
- usr/lib/icsf_stdll/pbkdf.h
The PKBDF2 implementation of the ICSF token is not correct, and thus can not be simply replaced by the OpenSSL implementation of PBKDF2.
Introduce a version field in ICCF's MK_SO and MK_USER files to be able to detect old version files. Old version files do not have a version field, but start with the total-length field right away. The length contained in the total-length field can be distinguished from a valid version value. That way we can still read old version files, but can also transparently support the new version files with the correct PKBDF2 implementation.
When writing ICSF MK_SO or MK_USER files, we always use the new version format. This allows a smooth transition to the new version. Just set new pins for SO and USER and the MK files are updated with the new version format. …
> ICSF: replace PBKDF implementation by libcrypto call

- usr/lib/common/p11util.c
- usr/lib/ep11_stdll/ep11_specific.c
To help debugging when the EP11 host lib does not like certain attribute settings.
> EP11: Trace EP11 blob attributes on Keygen, Unwrap, Derive

- usr/lib/common/h_extern.h
- usr/lib/common/loadsave.c
- usr/lib/common/obj_mgr.c
- usr/lib/common/object.c
- usr/sbin/pkcscca/pkcscca.c
The object name within a token object payload must match the file name it was loaded from. For private token objects (CKA_PRIVATE=TRUE) the object name is part of the encrypted payload.
A mismatch may indicate that the token object file has been tampered, for example due to a file rename or replacement. Don't load such objects, since this is most likely not the expected object that is being loaded.
> Validate object name when loading token objects

- usr/lib/common/h_extern.h
- usr/lib/common/host_defs.h
- usr/lib/common/loadsave.c
- usr/lib/common/obj_mgr.c
- usr/lib/common/utility.c
Do no longer use the pre-calculated next object name in the token's shared memory segment, but use a unique name generated by mkstemp instead. This guarantees unique file names, and the next object name to be used can not be tampered in the shared memory segment.
Existing token object files keep their names, only new files are created via mkstemp. There is no update/migration problem because files with old names and new names can live together without a problem.
The field used to contain the next token object name is kept in struct TOKEN_DATA but renamed to 'unused'. Removing this field would cause update/migration problems.
> Use mkstemp for unique token object name generation

- testcases/crypto/ec_func.c
EP11 can not derive keys less than 80 bits (10 bytes). This was formerly dependent on control point XCP_CPB_KEYSZ_BELOW80BIT, but this control point is now always OFF.
> TESTCASE: EC: Clarify on EP11 not deriving keys < 80 bits

- Makefile.am
'make uninstall' should also remove those config files, like the others.
> MAKEFILE: Also uninstall strength.conf and p11sak_defined_attrs.conf

- usr/lib/api/api_interface.c
- usr/sbin/pkcsconf/pkcsconf.c
Usually opencryptoki's own library context is freed during C_Finalize(). However, when an application does not call C_Finalize() before it exits, the cleanup is performed in the library destructor when the library is unloaded (i.e. during exit handlers).
OpenSSL also performs its own cleanup in exit handlers, and it may happen that OpenSSL cleanup is performed before the library destructors are called. This may cause crashes when Opencryptoki's library context has already been freed by OpenSSL cleanup, but the library destructor tries to free it a second time. This causes a double free, and very likely a crash.
Register an OpenSSL cleanup handler to clean up the library context before OpenSSL performs its own cleanup.
While we are at it, make sure pkcsconf calls C_Finalize() at the end of …
> Cleanup OpenSSL context in OpenSSL exit handler

- testcases/crypto/aes_func.c
- usr/lib/common/decr_mgr.c
- usr/lib/common/encr_mgr.c
- usr/lib/common/h_extern.h
- usr/lib/common/mech_aes.c
During C_EncryptInit and C_DecryptInit the AES-GCM mechanism parameter CK_GCM_PARAMS must be deep-copied into the operation context. The areas pointed to by fields pIv and pAAD may only be valid during C_EncryptInit/C_DecryptInit, but may be no longer valid for C_EncryptUpdate/C_DecryptUpdate and C_EncryptFinal/C_DecryptFinal. When the context is freed, the GCM parameter is also be deep-freed.
As far as I can tell AES-GCM is the only mechanism that needs this special handling at the moment. Mechanisms that have complex mechanism parameter structures but are used in single shot calls only (e.g. C_DeriveKey, C_WrapKey/C_UnwrapKey do not need a special handling, since its mechanism parameter is not copied into the context. Only mechanisms that are used with Init-Update-Final calls are …
> COMMON: Deep copy the AES-GCM mechanism parameter

- usr/lib/cca_stdll/cca_specific.c
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ica_s390_stdll/ica_specific.c
libica recently added function ica_cleanup to be called to free internal
OpenSSL 3.0 resources.
> ICA/EP11: Call ica_cleanup() if available

- usr/lib/cca_stdll/cca_specific.c
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ep11_stdll/ep11_specific.h
- usr/lib/ep11_stdll/new_host.c
- usr/lib/ica_s390_stdll/ica_specific.c
Calling dlclose() in a atfork handler may cause a deadlock. dlclose() may itself modify the atfork handler table to remove any fork handlers that the to be unloaded library has registered. Since the atfork handler table is currently locked when we are in an atfork handler, this would produce a deadlock.
> CCA/EP11/ICA: Do not use dlclose when in atfork handler

- doc/strength-example.conf
- tools/policyexamplegen.c
I would want to include this in the upcoming release.
> policy: Correct config file names in comments: .conf instead of .cfg

- usr/lib/ep11_stdll/ep11_specific.c
CKM_IBM_CPACF_WRAP is only supported/known inside the EP11 token code, but not externally, thus it is not in the mechtable. Add a special case for this mechanism in ep11_get_ckm() to avoid a warning trace message about that mechanism being unsupported.
> EP11: Make CKM_IBM_CPACF_WRAP known by ep11_get_ckm()

- usr/lib/common/mech_openssl.c
Need to import a KEYPAIR via EVP_PKEY_fromdata() when converting a RSA private key to an OpenSSL PKEY, not just the public key.
Having only the public key may cause failures when crypto operations are performed that require the private key, e.g. openssl_specific_rsa_decrypt().
Before OpenSSL commit https://github.com/openssl/openssl/commit/944f822aadc88b2e25f7695366810c73a53a00c8
this did work because it always imported all key parts, regardless of the selector specified.
> COMMON: Fix rsa_convert_private_key() for OpenSSL 3.0

- usr/lib/config/cfgparse.y
- usr/lib/config/configuration.c
- usr/lib/config/configuration.h
Similar to bare words, a bare number can appear outside of a list and represents its own configuration element.
With that the EP11 config file could also be parsed with the generic config file parser, instead of parsing it 'by hand'.
@juergenchrist Do you see any 'hidden' problems with adding this?
> config: Add support for bare numbers

- testcases/pkcs11/sess_mgmt.c
The sess_mgmt testcase uses CKM_MD5 as digest to test the session state. States of CKM_MD5 are not savable since code was changed to no longer use the deprecated OpenSSL MD5 API, but use OpenSSL's EVP API for MD5. The EVP API do no longer allow to export the digest state.
Use CKM_SHA256 instead, and also check for CKR_STATE_UNSAVEABLE on C_GetSessionState calls and skip the testcase if the state is (still) not savable.
The OpenSSL implementation of CKM_SHA256 does support savable states, unless built with OpenSSL >= 3.0.
> TESTCASE: Use CKM_SHA256 for C_GetSessionState tests

- usr/lib/ep11_stdll/ep11_specific.c
Does not happen in our test cases, but you never know what applications do.....
> EP11: CKA_DERIVE is not applicable for RSA, DSA, and DILITHIUM keys

- testcases/pkcs11/sess_opstate.c
When the operation state is not savable, the testcase is skipped. Make sure to return a zero return code anyway.
> testcases: Fix sess_opstate to return zero return code if skipped

- usr/lib/cca_stdll/cca_specific.c
According to the description of CCA verb "Digital Signature Verify" (CSNDDSV) in "Secure Key Solution with the Common Cryptographic Architecture Application Programmer's Guide Version 7.1" the signature verify request may also return 12 / 769 for bad signatures, in addition to 4 / 429. Treat both return codes as bad signature indication.
> CCA: EC signature verify may also return 12 / 769 for bad signatures

- testcases/crypto/aes.h
- testcases/crypto/aes_func.c
- usr/include/pkcs11types.h
- usr/lib/common/decr_mgr.c
- usr/lib/common/encr_mgr.c
- usr/lib/common/h_extern.h
- usr/lib/common/mech_aes.c
There is some confusion in the PKCS#11 standard, where the doc says nothing about this field, while the official C header has it:
https://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/include/pkcs11-v2.40/pkcs11t.h
Nevertheless, the header files contain the normative definition.
Add code to accept both versions of the CK_GCM_PARAMS structure, with or without the ulIvBits field. Detection is based on the size of the mechanism parameter. When a GCM mechanism parameter without the ulIvBits field is encountered, it is translated into a GCM parameter with that field, setting ulIvBits to ulIvLen * 8.
> Add field ulIvBits to CK_GCM_PARAMS, but also accept old version parameter

- testcases/unit/configdump.c
- usr/lib/config/cfgparse.y
- usr/lib/config/configuration.c
- usr/lib/config/configuration.h
This is a try to support parsing the EP11 token config file by adding special node types for a number pair list, and a number pair within a list. This can parse something like this:
```
APQN_ALLOWLIST # comment 1
8 13 # comment 2
10 13 # comment 3
END # comment 4
```
Makes handling in the consumer a little bit easier than just a series bare number constants.
While at it, remove the bare number const config element, as it causes problems and is no longer required, if we remove the `LOGLEVEL <value>` support from the EP11 config file (was removed in OCK v3.3 in 2015, and is since then allowed, but ignored and just produces a SYSLOG warning but has no effect). 
It still shows the one shift/reduce conflict which is caused by the single BARE element. Unfortunately the opencryptoki.conf already …
> config: support number pair lists and bare quoted strings

- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ep11_stdll/ep11_stdll.mk
The syntax of the EP11 token file stays the same, but for the following keywords the 'key = value' and 'key = "value"' form is also accepted:
CPFILTER, PKEY_MODE, DIGEST_LIBICA.
Furthermore, end of line comments (using '#') are now accepted at any places. Previously such comments were only accepted at the beginning of a line.
With this, only the EP11 CP-filter config file is still 'hand-parsed', all other config files use the generic config parser.
> Use generic config parser for parsing EP11 token config file

- .travis.yml
Builds start to fail in Travis due to 'The job exceeded the maximum log length, and has been terminated.' Reduce the output size by using a silent build.
> TRAVIS: Use silent build to reduce log file size

- testcases/crypto/ec_func.c
Due to improper return code handling in libica, an EC signature verification using an (intentionally) incorrect signature may return CKR_FUNCTION_FAILED when using the ICA token.
This has already been fixed in libica, but it may take a while until the fix arrives in the distro used in the CI. Until then the testcases would continue to fail. Temporarily accept CKR_FUNCTION_FAILED in the test case for this situation.
> TESTCASE: Accept CKR_FUNCTION_FAILED for invalid EC signatures with ICA token

- Makefile.am
- testcases/ciconfig.sh
- testcases/ock_tests.sh.in
Configure one CCA token and one EP11 token with the expected master/wrapping key verification patterns that are used in the CI. 
Also ensure that the CCA tokens are tested, even if catcher.exe is not currently running (catcher.exe is only needed for communication with the TKE, but not for using the CCA adapters).
> Add MKVPs/WKVP to generated configs for CI runs

- usr/sbin/pkcsconf/pkcsconf.c
Report left-over options that were not processed by getopt() as error, and do not silently ignore them.
> pkcsconf: Check for unrecognized or left-over options

- usr/lib/ep11_stdll/ep11_specific.c
For mixed card levels, the size query call and the call to obtain the list may run on different cards. When the size query call runs on a card with less mechanisms than the second call, will fail, but it returns the larger larger number of mechanisms.
The code already re-allocates the buffer for retrieving the mechanism list, but does not return the larger number in pulCount. This will lead to a CKR_BUFFER_TOO_SMALL when the application calls C_GetMechanismList
again to obtain the list of mechanisms, because the applications buffer is too small.
> EP11: Fix C_GetMechanismList returning CKR_BUFFER_TOO_SMALL

- usr/lib/config/cfgparse.y
- usr/lib/config/configuration.h
Then end string is not freed in a number pair list node leading to
a memory leak.
Minor unrelated changes in cfgparse.y that were noticed while at it.
Unit test configdump now runs leak free in valgrind or address sanitizer.
> config: Fix memory leak for number pair list nodes

- .gitignore
- Makefile.am
- testcases/misc_tests/p11sak_test.sh
- testcases/misc_tests/pkcsconf_test.sh
- testcases/unit/buffertest.c
- testcases/unit/unit.mk
- testcases/unit/uritest.c
- usr/lib/common/buffer.c
- usr/lib/common/buffer.h
- usr/lib/common/common.mk
- usr/lib/common/p11util.c
- usr/lib/common/p11util.h
- usr/lib/common/uri.c
- usr/lib/common/uri.h
- usr/lib/common/uri_enc.h
- usr/sbin/p11sak/p11sak.c
- usr/sbin/p11sak/p11sak.mk
- usr/sbin/pkcsconf/pkcsconf.c
- usr/sbin/pkcsconf/pkcsconf.mk
This PR contains a first implementation of the PKCS#11 URI generation support. It applies on top of my latest maint/autotools-cleanup branch. So please ignore patches 1-9/15.
First, a few generic helper functions are added, like a strlen-helper for non-null terminated strings in CK-structs and a string buffer with a dynamic memory management. Patch 12/15 contains the pkcs11 URI implementation. Patch 13-15/15 make use of it in the related tools.
As soon as maint/autotools-cleanup has been accepted and mergen into master, I'll provice a rebased version of this branch.
> v4: pkcs11 URI generation support

- .gitignore
Tools pkcsep11_migrate and pkcsep11_session must als be ignored.
> gitignore: update generated files to ignore

- man/man1/p11sak.1.in
- testcases/misc_tests/p11sak_test.sh
- usr/sbin/p11sak/p11sak.c
- usr/sbin/p11sak/p11sak.h
- usr/sbin/p11sak/p11sak_defined_attrs.conf
Where it makes sense strcmp() is changed to strcasecmp().
There is a new option --label at list-key command available, to filter by a key label. Closes: https://github.com/opencryptoki/opencryptoki/issues/501
Add support for IBM Dilithium keys.
> P11sak updates 2.0

- usr/sbin/p11sak/p11sak.c
- remove leftover debug printf.
- skip non-key objects during list-keys and remove-key, don't print ugly errors.
> p11sak fixes

- INSTALL
- README.md
Variables like 'prefix', 'libdir', or similar should not be specified with 'make', but should be specified with 'configure' instead. Specifying them with 'make' is not supported by the openCryptoki package and may produce unexpected results!
Suggested-by: @juergenchrist
> doc: Document that 'make prefix=/foo/bar' or similar is not supported

- .gitignore
- testcases/misc_tests/dual_functions.c
- testcases/misc_tests/misc_tests.mk
- testcases/ock_tests.sh.in
- usr/lib/common/h_extern.h
- usr/lib/common/host_defs.h
- usr/lib/common/lock_sess_mgr.c
- usr/lib/common/new_host.c
- usr/lib/common/sess_mgr.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/new_host.c
- Add support for functions C_DigestEncryptUpdate, C_DecryptDigestUpdate,
C_SignEncryptUpdate, and C_DecryptVerifyUpdate
- Fix C_Get/SetOperationState with multiple operations active
- Add a testcase for dual-function cryptographic functions
FYI: 
- For the first patch you only need to review one of the new_host.c file updates. The changes in the other 2 new_host.c files are exactly the same.
- For the second patch you only need to review the changes in lock_sess_mgr.c, the updates in sess_mgr.c are exactly the same.
- These semi-duplicated files are required because the files are not 100% the same, but the places where the updates of these commits are done are 100% the same.
> Add support for dual-function cryptographic functions

- usr/include/slotmgr.h
- usr/include/stdll.h
- usr/lib/api/api_interface.c
- usr/lib/api/apiproto.h
- usr/lib/api/apiutil.c
- usr/lib/common/utility.c
- usr/sbin/pkcsslotd/garbage_linux.c
- usr/sbin/pkcsslotd/shmem.c
Currently only CK_TOKEN_INFO.ulSessionCount is maintained with the total number of sessions open by a token, but ulRwSessionCount is set to CK_UNAVAILABLE_INFORMATION.
Besides the total number of sessions also maintain the number of R/W sessions, so that ulRwSessionCount can be returned with accurate information.
Similar as for the total number of sessions, the counter is kept in the shared memory segment of the pkcsslotd. It exists once as global counter, and once per process. When a process dies without unregistering from pkcsslotd, the garbage collector of pkcsslotd decrements the global counter by the amount of the per-process counter to keep the global counter consistent.
> Supply useful information in CK_TOKEN_INFO.ulRwSessionCount

- testcases/crypto/abfunc.c
Attribute bound keys are only supported by the EP11 token. When the abfunc testcase is run against a non-EP11 token, the entire testcase is skipped.
Print a "BEGIN xxx TESTCASE" message anyway, because otherwise the output post-processor for the CI will not see this as a new testcase, and report this skipped testcase under the testcase name from the previously run testcase.
> testcases: abfunc: Print BEGIN message even if entire test is skipped

- README.md
The TPM token is deprecated, because it supports only TPM version 1.2. Does not work with TPM version 2.0. We plan to remove the TPM token in a future openCryptoki release or version.
@dvelarde I hope I stated that correctly, please double check.
> TPM: Add deprecation notice to README.md

- usr/lib/common/utility.c
Function init_tokenInfo() is called when NVTOK.DAT is not existing when the token is initialized during C_Initialize. It then sets up the initial NV data. Always set flag CKF_USER_PIN_TO_BE_CHANGED in that case.
The code did check if the user pin was still uninitialized (i.e user_pin_sha all ASCII '0's) and set flag CKF_USER_PIN_TO_BE_CHANGED only if it was not initialized, but sets flag CKF_USER_PIN_INITIALIZED otherwise.
Unfortunately, with the new token data format, user_pin_sha is initialized to binary zeros from the initial memset, and thus init_tokenInfo() erroneously treated the user pin to be already initialized (binary zeros != ASCII '0's), and thus set flag CKF_USER_PIN_INITIALIZED instead of flag CKF_USER_PIN_TO_BE_CHANGED.
For the old data format init_token_data() initialized …
> common: CKF_USER_PIN_TO_BE_CHANGED must be set on a uninitialized token

- usr/lib/common/h_extern.h
- usr/lib/common/obj_mgr.c
- usr/lib/common/object.c
- usr/lib/common/tok_spec_struct.h
- usr/lib/common/tok_specific.h
- usr/lib/ep11_stdll/ep11_specific.c
Like other EP11 host library functions that operate on key blobs, m_GetAttributeValue and m_SetAttributeValue as well as m_UnwrpKey with CKM_IBM_CPACF_WRAP may also return CKR_SESSION_CLOSED when the EP11 session that the key blob is bound to is not logged in into the adapter that is currently used for the request.
For that the session must be passed through to the functions.
> EP11: Handle m_Get/m_SetAttributeValue and protected key derive with session bound blobs

- usr/lib/common/asn1.c
It could happen in error cases, that the "len" variables in some functions are used uninitialized. Set len to 0 in all cases, where this could happen.
This also fixes some warnings, if newer compilers are used.
Signed-off-by: Holger Dengler <dengler@linux.ibm.com>
> lib: asn1: initialize len variables

- usr/lib/ep11_stdll/ep11_specific.c
Fail the EP11 token init if neither APQN_ALLOWLIST nor APQN_ANY is specified, or if APQN_ALLOWLIST but no APQN is specified.
> EP11: Fail token init if EP11 token config file has missing APQN settings

- usr/lib/api/api_interface.c
In case an OpenSSL function failed inside of the API function, the OpenSSL error stack should show the reasons for the failure.
Please note that an error on the OpenSSL error stack does not necessarily mean that an error has happened that would cause the API function to fail. Some error situations are expected and internally handled, and do not lead to a failure of the API function.
> API: Trace OpenSSL error stack on return from API function

- testcases/misc_tests/pkcsconf_test.sh
The script uses functions/commands, which are only available in bash. Change the interpreter line accordingly.
Signed-off-by: Holger Dengler <dengler@linux.ibm.com>
> testcases: pkcsconf_tests.sh: fix interpreter

- usr/lib/common/obj_mgr.c
- usr/lib/ep11_stdll/ep11_specific.c
- pass back chain code in mech param
- supply SPKI when deriving public key
- supply SPKI for private key import (all asym key types)
> EP11: fixes for CKM_IBM_BTC_DERIVE 

- usr/lib/ep11_stdll/ep11_specific.c
Function publ_key_get_spki() allocates the SPKI buffer, so it must be freed afterwards.
> EP11: Fix memory leak introduced with recent commit

- usr/sbin/p11sak/p11sak.c
Command 'p11sak generate-key ibm-dilithium' segfaults because the dilithium version is not specified, but the code does not check for a NULL pointer.
> p11sak: Fix segfault when dilithium version is not specified with generate-key

- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ica_s390_stdll/ica_specific.c
With some temporary code tweaking (comment asm statements out, replace libica calls with dummy functions, etc), I was able to build the EP11 and ICA tokens on x86 as well, and thus let Coverty find problems there as well.
> More Coverty fixes (for EP11 and ICA tokens)

- usr/lib/common/mech_aes.c
Compiles may warn about a possibly uninitialized variable. This is a false positive, the variable is initialized in the code path where it is used. Zeroize the variable on the declaration to silence this warning.
```
usr/lib/common/mech_aes.c: In function 'aes_xts_cipher': usr/lib/common/mech_aes.c:4320:13: error: 'iv_prev' may be used uninitialized in this function [-Werror=maybe-uninitialized]
memcpy(iv, iv_prev, AES_BLOCK_SIZE);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Silence maybe-uninitialized warning

- man/man1/pkcscca.1.in
- usr/sbin/pkcscca/pkcscca.c
- usr/sbin/pkcscca/pkcscca.h
Up to opencryptoki version 3.14.0, RSA keys where created using the RSA-CRT key token format (private key section X'08'). RSA-CRT keys are encrypted with the CCA ASYM master key, and can not be used for certain mechanisms, e.g.
RSA-PSS or RSA-OAEP. In newer opencryptoki versions, RSA keys are created using the RSA-AESC key token format (private key section X'31'). RSA-AESC keys are encrypted with the CCA APKA master key. Up to version 3.16.0, RSA public keys also contained full CCA secure key tokens, including the private key section (which is encrypted by the CCA master key). 
- Add a migration option to convert old RSA-CRT keys to the new RSA-AESC key token format, as well as extract the public key from the key tokens of RSA public key objects that contain a full key token.
- Handle …
> Updates and fixes for the pkcscca tool

- usr/lib/config/config.mk
- usr/sbin/pkcsicsf/pkcsicsf.mk
Fixes https://github.com/opencryptoki/opencryptoki/issues/636 from @mhartmay and another bug with the parser generation in out of tree builds.
> Fixes for out of tree build

- usr/lib/ep11_stdll/ep11_specific.c
The very last control point must also be applied from the queried bits to the combined bits. Otherwise the very last control point is always treated as being ON, although it might be OFF, and this can lead to mechanisms being used that are disabled by that control point.
Fixes https://github.com/opencryptoki/opencryptoki/commit/97248f73495695436f11fafd74c2ec41a5a6f796
This caused failures in the CI last night.
> EP11: Fix setting unknown CPs to ON

- usr/lib/ep11_stdll/ep11_specific.c
Data or Certificate objects do not have a key type(CKA_KEY_TYPE). So, Key type should be fetched after the switch case to handle this.
Signed-off-by: Vishnudatha Kanjur <kanjur@ibm.com>
> EP11: Fix set attribute values function for Data or Certificate objects.

- testcases/crypto/aes_func.c
Running them on other tokens, that do not support pkey=1 will just produce lots of skip messages, but has no real use.
The same is already done in the EC testcases.
> TESTCASES: run AES pkey=1 tests only on EP11 token

- misc/misc.mk
Don't prefix with destination directory, as this would produce an invalid directory. This would for example cause rpmbuild to fail.
Autoconf prefixes it with the destination directory automatically.
> configure: Fix install location of tmpfiles.d config file

- testcases/crypto/dilithium_func.c
- testcases/crypto/kyber_func.c
- usr/lib/common/pqc_defs.h
- usr/lib/common/pqc_supported.c
Some compiler versions report error "error: initializer element is not constant" for the PQC initializers.
Use sizeof() directly in the initializer, instead of declaring a global variable holding the size. Such a global variable is not always considered as a constant, although it is declared as const.
> Fix compile error "error: initializer element is not constant"

- usr/lib/icsf_stdll/icsf.c
- usr/lib/icsf_stdll/icsf_specific.c
For wrapping/unwrapping with a symmetric wrapping key using mechanisms CKM_DES_CBC_PAD, CKM_DES3_CBC_PAD, or CKM_AES_CBC_PAD the IV (i.e. the mechanism parameter) must be passed to ICSF as well.
> ICSF: misc fixes

- usr/sbin/pkcsconf/pkcsconf.c
Certain options cause pkcsconf to also list slots that have no token present, i.e. those options that list slots (versus tokens). If options that list slots are combined with options that list tokens, do not fail when attempting to display token information on a slot that has no token present.
> pkcsconf: Ignore CKR_TOKEN_NOT_PRESENT when displaying info

- usr/lib/common/pkey_utils.c
- usr/lib/common/pkey_utils.h
- usr/lib/ep11_stdll/ep11_specific.c
When pkey_attr has been allocated by ep11tok_pkey_skey2pkey(), but afterwards, the verification pattern check fails, or pkey_update_and_save() fails without adding the attribute to the object, then pkey_attr must be freed.
> EP11: Fix possible memory leak

- usr/lib/ica_s390_stdll/ica_specific.c
The 'p' component in the libica CRT private key is padded with 8 bytes. 
Correct the conversion of the 'p' component into an OpenSSL BIGNUM by skipping the first 8 bytes of padding.
Unfortunately this is no where documented, one needs to 'know' that there is an 8 bytes padding for 'p', 'dp', and 'qInverse'.
This fixes an error during private exponent calculation at RSA key generation when BN_mod_inverse() returns an error, reporting that no inverse exists, because the 'p' component is wrong.
Fixes: b9ae1f6efbef ("ICA: Calculate private exponent when generating RSA keys")
@jschmidb Maybe you could add information about this 8 bytes padding to the libica header file and/or manual?
> ICA: Fix private exponent calculation

- testcases/ciconfig.sh
Some mechanisms are only available on a CEX8 crypto card. Let slot 45 use only CEX8 cards.
> ci: switch to CEX8 as latest crypto express adapter version

- usr/lib/ep11_stdll/ep11tok.conf
The ep11 pkey_mode option also supports EC keys.
> EP11: fix description of PKEY_MODE option

- rpm/opencryptoki.spec
- usr/sbin/pkcsslotd/slotmgr.c
Create the /var/lib/opencryptoki/HSM_MK_CHANGE/ directory during RPM install and check for it also during pkcsslotd startup.
> COMMON: Create HSM_MK_CHANGE directory in RPM and at pkcsslotd startup

- usr/lib/hsm_mk_change/hsm_mk_change.c
If the OCK_HSM_MK_CHANGE_LOCK_FILE has already been created by another user, just open it. Only if it is not existent, try to create it and set the permissions.
While open(... , O_CREAT | O_RDONLY) also works for an already existing file, setting the permissions may fail if the file is owned by another user. However, when the file already exists, we can assume that the permissions are set correctly already.
> hsm_mk_change: Try to open existing lock file before creating it

- usr/lib/ep11_stdll/ep11_specific.c
Do not fail if a concurrent master key change is active but no re-enciphered key blob (attribute CKA_IBM_OPAQUE_REENC) is (not yet) available. This is a possible situation and is not an error case. Leave skey_reenc_attr = NULL in this case, and ep11tok_pkey_skey2pkey() and the ep11tok_pkey_wrap_handler() will take care abut this.
> EP11: Fix ep11tok_pkey_update to not fail if no reenc blob is available

- usr/include/local_types.h
- usr/lib/api/api_interface.c
- usr/lib/api/apiutil.c
- usr/lib/common/btree.c
- usr/lib/common/lock_btree.c
- usr/lib/common/new_host.c
- usr/lib/ep11_stdll/new_host.c
- usr/lib/icsf_stdll/icsf_specific.c
- usr/lib/icsf_stdll/new_host.c
Check errors for all RW-lock or mutex initialization calls, and perform proper error handling and cleanup if it fails.
> Covertiy fixes

- testcases/crypto/des3_func.c
- usr/lib/common/mech_ec.c
The EP11 token claims to support CKM_PBE_SHA1_DES3_EDE_CBC, so lets make it really work and add a testcase for it.
> Support CKM_PBE_SHA1_DES3_EDE_CBC for EP11

- configure.ac
Library libcap is only needed by pkcsslotd, bot not by all the other executables.
AC_CHECK_LIB without a 'action-if-found' specified will add the library to the global LIBS, and thus all executables will link against it. Avoid this by specifying a 'action-if-found' action and build a LIBCAP_LIBS variable (which however is unused).
> configure: Don't add libcap to LIBS globally

- usr/lib/common/h_extern.h
- usr/lib/common/key.c
- usr/lib/ep11_stdll/ep11_specific.c
Older EP11 card generations don't seem to like RSA CRT keys with p < q. Check for such keys during clear key import, and swap its CRT components and recalculate qInv (CKA_COEFFICIENT).
> EP11: Handle RSA clear key import for key with p < q

- usr/lib/common/cert.c
The code did not set a default value for CKA_JAVA_MIDP_SECURITY_DOMAIN, but incorrectly set CKA_TRUSTED twice.
Similar CKA_NAME_HASH_ALGORITHM was not set, but CKA_CERTIFICATE_CATEGORY was set twice, and with a wrong size.
> Correctly set default attributes for certificates

- usr/lib/ep11_stdll/ep11_mkchange.c
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ep11_stdll/ep11_specific.h
When re-enciphering session-bound key blobs, the EP11 session must be logged in into the APQN where the re-encipher command is performed with. In case the session is not logged in CKR_SESSION_CLOSED is returned.
Pass the corresponding session to the re-encipher function and add a retry logic in case of CKR_SESSION_CLOSED to re-login the session.
> EP11: Re-enciphering session-bound key blobs require the session to be logged in

- testcases/crypto/ec_func.c
Remove the created EC keys when the test step is complete, don't leave them hanging around.
> TESTCASES: Remove EC key objects after test step

- usr/sbin/p11sak/p11sak.c
An RSA-PSS key can be generated via:
`openssl genpkey -algorithm rsa-pss -pkeyopt rsa_keygen_bits:2048  -out rsapss.pem`
Generating a certificate with this key resuts in a certificate that contains an RSA-PSS key.
> More p11sak fixes

- usr/lib/api/api_interface.c
Ensure OpenSSL is initialized and the OpenSSL config is loaded BEFORE creating OpenCryptoki's own library context. Otherwise the OpenSSL config is loaded later, which may cause that all configured providers are also loaded into the library context. We intentionally want to use only the default and legacy provider for OpenCryptoki's software crypto operations. So loading other providers into our context may cause that those other providers are used instead. In worst case this may cause a recursion, e.g. when a PKCS#11 provider is loaded routing the crypto calls back to OpenCryptoki.
> Ensure OpenSSL config is loaded before creating own library context

- usr/lib/cca_stdll/ccatok.conf
- usr/lib/ep11_stdll/ep11tok.conf
For both tokens, AES-XTS is only supported via protected keys. Other operation modes, like ECB and CBC, are just accelerated via the PKEY_MODE option.
> CCA/EP11: add info about AES-XTS to token config files

- testcases/crypto/abfunc.c
When running the abfunc test, one EC private key was left over, because the test creates 16 keys, but NUMKEYS was 15.
> TESTCASES: abfunc test did leave one EC key over

- testcases/misc_tests/cca_export_import_test.c
- testcases/policy/policytest.c
A total of 17 keys were left over in the CCA token repository when running the cca_export_import_test.
> TESTCASES: cca_export_import_test did leave RSA and EC keys over

- usr/sbin/p11sak/p11sak.c
Include attributes CKA_IBM_PROTKEY_EXTRACTABLE ('K') and CKA_IBM_PROTKEY_NEVER_EXTRACTABLE ('Z') into the list of attributes that can be used for filtering keys.
However, only CKA_IBM_PROTKEY_EXTRACTABLE ('K') can be used for setting attributes.
CKA_TRUSTED can be used for setting attributes, but it can only be set to TRUE by the SO user.
> p11sak: Correct help texts for attributes

- misc/misc.mk
Do not let tmpfiles.d create the token specific directories inside /var/lock/opencryptoki/. It is not known during build time which tokens will exist later during run time. A user may configure any number of tokens with any names in /etc/opencryptoki/opencryptoki.conf.
The API layer will create any non-existing token specific lock directories inside /var/lock/opencryptoki/ during C_Initialize() as needed.
> tmpfiles.conf: Do not create token specific dirs inside /var/lock/opencryptoki/

- usr/lib/ep11_stdll/ep11_specific.c
- usr/sbin/pkcsep11_session/pkcsep11_session.c
When checking if a card or an APQN is online, not only check the 'online' sysfs attribute, but also check the 'config' and 'chkstop' attribute. Cards and APQNs in check-stopped or deconfigured state can still be reported as online via the sysfs attribute, although they are not available to be used for the EP11 token.
In case the 2 additional sysfs attributes are not available in sysfs, then don't fail, but rely on the 'online' attribute only.
> EP11: Also check for deconfigured and check-stopped cards

- usr/lib/tpm_stdll/tpm_openssl.c
Set NULL to OpenSSL BIGNUM pointers as initial value. Otherwise it will crash in OpenSSL libary when invoking openssl_get_modulus_and_prime function.
> TPM: Fix issue caused by uninitialized variables

- testcases/misc_tests/cca_export_import_test.c
- usr/lib/cca_stdll/cca_specific.c
- usr/sbin/pkcscca/pkcscca.c
On the s390x platform this does not make a difference, since s390x is big endian itself. However, on little endian platforms care must be taken to convert such fields to the correct endianness.
> CCA: All numeric fields in CCA key tokens and verb-data are big endian

- usr/lib/cca_stdll/cca_specific.c
- usr/lib/cca_stdll/cca_stdll.h
- usr/lib/cca_stdll/ccatok.conf
- usr/lib/common/h_extern.h
- usr/lib/common/key_mgr.c
- usr/lib/ep11_stdll/ep11_specific.c
**EP11:** 
When a secret key (CKO_SECRET_KEY) or a private key (CKO_PRIVATE_KEY) is generated with CKA_SENSITIVE=TRUE and/or CKA_EXTRACTABLE=FALSE then set CKA_ALWAYS_SENSITIVE to TRUE and/or CKA_NEVER_EXTRACTABLE to TRUE accordingly.
This is the same as done by common code in key_mgr_generate_key() and key_mgr_generate_key_pair(). Factor-out this code and make a separate function out of it that can be called from the EP11 token.
**EP11+CCA:** 
The PKCS#11 standard defines that the default value for CKA_SENSITIVE is FALSE for secret keys (CKO_SECRET_KEY), and for private keys (CKO_PRIVATE_KEY) the default is token dependent.
If the FORCE_SENSITIVE token option is enabled, set attribute CKA_SENSITIVE to TRUE for secret keys (CKO_SECRET_KEY) if it is not specified in the template. This is …
> EP11/CCA: Fixes and change regarding CKA_SENSITIVE and CKA_EXTRACTABLE defaults

- testcases/crypto/digest_func.c
- testcases/crypto/dilithium_func.c
- testcases/crypto/kyber_func.c
When running the digest tests against the EP11 token, the number of passed tests is greater than the number of ran tests:
`Total=849, Ran=365, Passed=389, Failed=0, Skipped=484, Errors=0`
Fix this by adding a call to testcase_new_assertion() at the right place to ensure the ran counter is increased before a test is counted as being passed or failed.
This is only seen with the EP11 token because only the EP11 token currently supports mechanisms CKM_SHAnnn_KEY_DERIVATION. The tests for those mechanisms are missing the testcase_new_assertion() to increase the ran counter.
> TESTCASE: Correct test run counting for digest test

- usr/lib/ica_s390_stdll/ica_specific.c
When the system is in FIPS mode, newer libica versions may prevent AES-GCM from being used with an external IV. FIPS requires that the AES-GCM IV is created libica internally via an approved random source.
The ICA token can not support the internal generation of the AES-GCM IV, because the PKCS#11 mechanism CKM_AES_GCM does not allow this.
Enable the use of external AES-GCM IVs for libica, if the used libica library supports this. Newer libica versions support to allow external AES-GCM IVs via function ica_allow_external_gcm_iv_in_fips_mode().
> ICA: Enable external AES-GCM IV when libica is in FIPS mode

- testcases/misc_tests/events.c
When running the events test the number of passed tests is 10, but the 'total' and 'ran' tests is 1.
Total=1, Ran=1, Passed=10, Failed=0, Skipped=0, Errors=0
Fix this by adding a call to testcase_new_assertion() at the right places to ensure the ran counter is increased before a test is counted as being passed or failed.
> TESTCASE: Correct test run counting for the events test case

- usr/lib/common/mech_ec.c
- usr/lib/common/template.c
- usr/lib/ica_s390_stdll/ica_specific.c
- usr/lib/soft_stdll/soft_specific.c
- usr/lib/tpm_stdll/tpm_openssl.c
- usr/sbin/p11sak/p11sak.c
For OpenSSL BIGNUMs containing sensitive private key material, use BN_secure_new() to allocate the BIGNUM on OpenSSLs secure heap.
Also clean any buffers that might contain sensitive data before freeing it.
> Fixes for protecting buffers containing sensitive data

- testcases/crypto/crypto.mk
- testcases/crypto/ec_func.c
- usr/lib/common/h_extern.h
- usr/lib/common/mech_ec.c
- usr/lib/ep11_stdll/ep11_specific.c
For secure key tokens, the derived secret can not be compared with the expected key value for known answer tests (KATs), because the derived secret is a secure key that never reveals its key value in clear.
However, the test can calculate an HMAC of some know data using the derived key as well as with the expected key value from the KAT. If both keys are the same, then the calculated HMAC must also be the same.
> TESTCASES: ec_tests: Support ECDH KATs for secure key tokens

- testcases/crypto/dilithium_func.c
- testcases/crypto/ec_func.c
- testcases/crypto/kyber_func.c
- testcases/crypto/rsa_func.c
- testcases/pkcs11/get_interface.c
- tools/tableidxgen.c
- usr/lib/api/socket_client.c
- usr/lib/common/mech_openssl.c
- usr/lib/hsm_mk_change/hsm_mk_change.c
- usr/lib/icsf_stdll/icsf.c
- usr/lib/icsf_stdll/icsf.h
- usr/lib/icsf_stdll/icsf_specific.c
- usr/sbin/p11sak/p11sak.c
- usr/sbin/p11sak/p11sak.h
- usr/sbin/pkcshsm_mk_change/pkcshsm_mk_change.c
- usr/sbin/pkcstok_migrate/pkcstok_migrate.c
usr/lib/common/mech_openssl.c:2425:51:
error: passing argument 5 of 'EVP_PKEY_get_octet_string_param' from
incompatible pointer type
Change ecpoint_len to type size_t instead of CK_ULONG to match the expected type used by EVP_PKEY_get_octet_string_param(). Also, for the further use of that variable it is OK to use size_t.
> common: Fix compile error/warning when compiled with GCC 14

- usr/lib/ica_s390_stdll/ica_specific.c
The data attached to an object of the ICA token is of size sizeof(ica_ex_data_t), not sizeof(ica_private_data_t).
> ICA: Fix length check for ICA ex-data

- usr/lib/common/mech_openssl.c
An RSA key object that has no CKA_PRIVATE_EXPONENT may either don't have that attribute at all, or may have an empty CKA_PRIVATE_EXPONENT attribute. Both situations should be handed the same, and the private exponent of the key needs to be calculated from the other key components.
Note that RSA key objects generated with a current soft or ICA token will always have a valid CKA_PRIVATE_EXPONENT attribute, since this is provided during key generation.
> COMMON: Fix implicit rejection with RSA keys with empty CKA_PRIVATE_EXPONENT

- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ep11_stdll/ep11_specific.h
- usr/lib/ep11_stdll/ep11_stdll.mk
- usr/lib/ep11_stdll/ep11tok.conf
- usr/lib/ep11_stdll/tok_struct.h
This pull request adds the following fixes and enhancements:
- Add two new parameter values ENABLE4EXTR and ENABLE4ALL to the ep11token PKEY_MODE config option. Older ep11 card firmware enforces the restriction that keys can not have CKA_EXTRACTABLE=true and CKA_IBM_PROTKEY_EXTRACTABLE=true at the same time. With newer card firmware this restriction is removed and a new control point is introduced to allow checking for this feature.
- On 32-bit s390 platforms, the pkey related assembler code parts won't compile. Therefore, add NO_PKEY compile switches where necessary. The NO_PKEY compile switch is already handled in configure.ac.
- The XCP_MFL_PROBE flag is no longer needed for host libs > 4.0, so add a check for this and don't specify the flag for newer libraries.
> EP11 pkey option: misc fixes and enhancements 

- usr/lib/common/decr_mgr.c
- usr/lib/common/dig_mgr.c
- usr/lib/common/encr_mgr.c
- usr/lib/common/sign_mgr.c
- usr/lib/common/verify_mgr.c
The context_len field of an encrypt/decrypt, sign/verify, or digest context should not be set to zero before the context_free_func callback is called. This callback gets the context_len as argument, so setting it to zero before calling the callback may cause problems inside the callback.
Currently, none of the callbacks used makes use of the context length, so this does not actually cause any problems. However, future callbacks might rely on the context length being passed correctly.
> COMMON: Don't clear context_len before calling context_free_func

- usr/lib/cca_stdll/cca_specific.c
Add support for the Koblitz curve secp256k1 into function check_cca_ec_type_and_add_params() that is used to detect the curve used by the secure key blob to import.
This is a left over from PR https://github.com/opencryptoki/opencryptoki/pull/751
> CCA: Support import of key blob for private EC key with Koblitz curve secp256k1

- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ep11_stdll/ep11_specific.h
- usr/lib/ep11_stdll/new_host.c
In case the control point setting of the adapters do not allow that attributes CKA_EXTRACTABLE and CKA_IBM_PROTKEY_EXTRACTABLE are both true, then reject this with CKR_ATTRIBUTE_VALUE_INVALID.
The EP11 code would reject that with CKR_FUNCTION_CANCELED, which for EP11 it means that it violates an internal policy (i.e. control point settings), but in PKCS#11 this return code has a totally different meaning. So reject such situations explicitly with the correct return code.
> EP11: Reject combined extract attribute settings if it is not supported

- Makefile.am
- testcases/ciconfig.sh
- testcases/common/common.c
- testcases/crypto/aes_func.c
- testcases/crypto/ec_func.c
- testcases/ock_tests.sh.in
A new parameter -combined-extract is introduced for the testcases. If this parameter is specified, the CKA_IBM_PROTKEY_EXTRACTABLE attribute is always set to TRUE for new key objects. Note that testcases will fail if combined extract is not supported in the test environment! In addition to this, a new token setup is added to ciconfig.sh to enable combined extract tests in the CI.
> TESTCASES: Enable AES and EC tests for combined extract

- usr/sbin/p11sak/p11sak.c
Copying an empty (zero length) CKA_ID attribute does not make much sense, because the default CKA_ID value is empty anyway.
As reported by @akulhalli in https://github.com/opencryptoki/opencryptoki/pull/749#issuecomment-2031165150
> p11sak: Don't copy an empty CKA_ID with extract-pubkey

- man/man1/p11sak.1.in
- testcases/misc_tests/p11sak_test.sh
- usr/lib/common/uri.c
- usr/lib/common/uri.h
- usr/sbin/p11sak/p11sak.c
- usr/sbin/p11sak/p11sak.h
The pkcs11-provider from https://github.com/latchset/pkcs11-provider supports PEM files containing the PKCS#11 URI instead of the key or certificate material. Enhance p11sak to allow to export such URI-PEM files, optionally including the PKCS#11 user pin via `pin-value` (insecure) or `pin-source` query attribute of the URI.
@jschmidb Please give it a try if such a URI-PEM (with or without the pin) generated by p11sak really works with the pkcs11-provider.
> p11sak: Add support to export a key or certificate as URI-PEM

- usr/lib/common/mech_aes.c
- usr/lib/ica_s390_stdll/ica_specific.c
The new libica gcm api (ica_aes_gcm_kma_*) exploits the KMA instruction on z14 and later. This results in better performance.
> Support new gcm API in icatoken

- usr/lib/cca_stdll/cca_specific.c
Its not used by the CCA token code and it is not available in the libcsulcca.so CCA library, but only in libcsulccamk.so.
> CCA: Do not try to load CCA function CSNBMKP

- README.md
Don't enclose it in single quotes, and add query parameter (which is ignored) to avoid caching of outdated image.
> README.md: Fix Coverity badge

- .travis.yml
Ubuntu 'jammy' (22.04) comes with OpenSSL 3.0, which is what most distributions use nowadays as well. However, it must still be ensured that it builds with OpenSSL 1.1.1. Add one job to run on Ubuntu 'focal' (20.04) that still comes with OpenSSL 1.1.1. Build this on s390x only, since this covers the largest set of source files to be built. If it builds on s390x, then it should also build on other architectures.
> TRAVIS: Add one more job to build with OpenSSL 1.1.1

- testcases/common/common.c
- testcases/crypto/rsa_func.c
- usr/lib/cca_stdll/cca_specific.c
- usr/lib/common/h_extern.h
- usr/lib/common/key.c
- usr/lib/common/mech_openssl.c
- usr/sbin/pkcscca/pkcscca.c
PKCS#11 is flexible with respect to which attributes must be present in an RSA key. Keys can be specified in Chinese-Remainder format or they can be specified in modular-exponent format. Effective with version 2.40, tokens MUST also store CKA_PUBLIC_EXPONENT. This permits the retrieval of sufficient data to reconstitute the associated public key.
When creating an RSA private key via C_CreateObject: either all CRT attributes must be specified, or none of them. Specifying only some of them is invalid and causes CKR_TEMPLATE_INCONSISTENT. As per PKCS#11 v2.40, attributes CKA_MODULUS, CKA_PRIVATE_EXPONENT and CKA_PUBLIC_EXPONENT must always be specified.
> Support to import RSA keys with ME components only

- usr/lib/icsf_stdll/icsf.c
- usr/lib/icsf_stdll/icsf_specific.c
Fix covscan warnings on cases like 'if (a - b > 0)' where both 'a' and 'b' are unsigned types. In case 'b' is larger than 'a', then the subtraction result may overflow because the result is also treated as unsigned type. Fix this by using 'if (a > b)' instead.
Note that in the changed places 'a' is always larger than or equal to 'b' so the overflow does not happen. Still, changing the code to be less error-prone is a good thing.
Closes: https://github.com/opencryptoki/opencryptoki/issues/782
Suggested-by: @ngothan
> ICSF: Fix covscan findings on potential integer overflows

- usr/lib/cca_stdll/cca_specific.c
CCA error 8/2053 means "No message found in the OAEP-decoded data" and is an additional error (in addition to the already handled 8/2054 error: "There is a non-valid RSA Enciphered Key cryptogram: OAEP optional encoding parameters failed validation") that could be returned by CCA verb CSNDPKD in case of RSA-OAEP on invalid encoded messages.
Translate this error also to CKR_ENCRYPTED_DATA_INVALID to not allow any distinction between these two error situations. Until now 8/2053 was translated to CKR_FUNCTION_FAILED, like any other CCA error codes.
> CCA: Also treat RSA-OAEP error 8/2053 as CKR_ENCRYPTED_DATA_INVALID

- testcases/common/common.c
Field ulDeviceError in struct CK_SESSION_INFO might be set in case of a CKR_FUNCTION_FAILED. This can be due to a policy rejection (ulDeviceError is CKR_POLICY_VIOLATION), or due to other token internal errors.
Print the value of ulDeviceError in case its non-zero and not indicating a policy error.
> TESTCASES: Print CK_SESSION_INFO.ulDeviceError in case of CKR_FUNCTION_FAILED

- usr/lib/common/key.c
For the IBM Kyber key type, the CKA_IBM_KYBER_SK attribute contains the private key and thus, this attribute is sensitive. Attribute CKA_IBM_KYBER_PK contains the public key and is not sensitive.
Fixes: https://github.com/opencryptoki/opencryptoki/commit/f8ad4f039599ebe1f86381449eea885497ba05a2
> COMMON: Fix sensitive IBM Kyber attribute

- testcases/misc_tests/misc_tests.mk
Fixes 'make distcheck' failure "make[2]: *** No rule to make target 'testcases/misc_tests/ibm-dilithium-key.pem', needed by 'distdir-am'.  Stop."
Fixes: https://github.com/opencryptoki/opencryptoki/commit/2fc60422b8178b0abc2802baf0bc163f660dd60a
> TESTCASES: Fix EXTRA_DIST for renamed PEM files

- usr/lib/api/policy.c
- usr/lib/api/statistics.c
Policy and statistics code has a need to check certain fields of the mechanism parameter structures. Check for correct mechanism parameter length and pointer before attempting to access the mechanism parameter fields. This avoids seg-faults in case an application passes an invalid mechanism parameter.
> POLICY/STATISTICS: Check mech parameter length and pointer before accessing it

- man/man1/man1.mk
- man/man5/man5.mk
- man/man7/man7.mk
- man/man8/man8.mk
When using 'make dist', only distribute the man page sources, i.e. the *.in files, but not the generated man page files. Mentioning them in EXTRA_DIST is not necessary, because they are input to AC_CONFIG_FILES in configure.ac, and thus are distributed automatically.
> MAKEFILE: Do not distribute generated man page files

- man/man1/p11sak.1.in
- testcases/misc_tests/always_auth.c
- testcases/misc_tests/misc_tests.mk
- testcases/ock_tests.sh.in
- usr/include/pkcs11types.h
- usr/lib/common/decr_mgr.c
- usr/lib/common/encr_mgr.c
- usr/lib/common/h_extern.h
- usr/lib/common/host_defs.h
- usr/lib/common/key.c
- usr/lib/common/key_mgr.c
- usr/lib/common/mech_ec.c
- usr/lib/common/mech_rsa.c
- usr/lib/common/mech_ssl3.c
- usr/lib/common/new_host.c
- usr/lib/common/sign_mgr.c
- usr/lib/common/template.c
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ep11_stdll/ep11_specific.h
- usr/lib/ep11_stdll/new_host.c
- usr/sbin/p11sak/p11sak.c
This PR adds support for the CKA_ALWAYS_AUTHENTICATE attribute.
CKA_ALWAYS_AUTHENTICATE can be set for a private key object (i.e. an object of class CLO_PRIVATE_KEY), and if it si TRUE, then the user must authenticate on each 'use' of that key. 
From https://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959719:
> The CKA_ALWAYS_AUTHENTICATE attribute can be used to force re-authentication (i.e. force the user to provide a PIN) for each use of a private key. “Use” in this case means a cryptographic operation such as sign or decrypt. This attribute may only be set to CK_TRUE when CKA_PRIVATE is also CK_TRUE.
> 
> Re-authentication occurs by calling C_Login with userType set to CKU_CONTEXT_SPECIFIC immediately after a cryptographic operation using the key …
> Add support for CKA_ALWAYS_AUTHENTICATE

- testcases/common/common.c
- testcases/crypto/ec_func.c
- usr/lib/cca_stdll/cca_specific.c
- usr/lib/cca_stdll/cca_stdll.h
- usr/lib/common/mech_aes.c
- usr/lib/common/pkey_utils.c
- usr/lib/common/pkey_utils.h
- usr/lib/common/tok_spec_struct.h
- usr/lib/common/tok_specific.h
- usr/lib/ep11_stdll/ep11_specific.c
- usr/lib/ica_s390_stdll/ica_specific.c
- usr/lib/soft_stdll/soft_specific.c
This pr adds support for  live guest relocations (LGR) for protected key operations to the CCA and EP11 tokens.
> Support live guest relocations for protected key ops

- usr/lib/common/mech_openssl.c
usr/lib/common/mech_openssl.c:4751:36: error: passing argument 2 of 'get_sha_size' from incompatible pointer type [-Wincompatible-pointer-types] 4751 | rc = get_sha_size(digest_mech, &mac_len);
usr/lib/common/mech_openssl.c:4851:36: error: passing argument 2 of 'get_sha_size' from incompatible pointer type [-Wincompatible-pointer-types] 4851 | rc = get_sha_size(digest_mech, &mac_len);
Closes: https://github.com/opencryptoki/opencryptoki/issues/809
> COMMON: Fix compile error due to incompatible pointer types

- usr/lib/common/mech_dh.c
- usr/lib/common/mech_ec.c
- usr/sbin/pkcscca/pkcscca.c
There are 2 resource leaks in opencryptoki-3.24.0 found by covscan:
```
1. Defect type: RESOURCE_LEAK
4. opencryptoki-3.24.0/usr/sbin/pkcscca/pkcscca.c:740:5: alloc_fn: Storage is returned from allocation function "malloc".
5. opencryptoki-3.24.0/usr/sbin/pkcscca/pkcscca.c:740:5: var_assign: Assigning: "new_key->opaque_attr" = storage returned from "malloc(attrs[0].ulValueLen)".
7. opencryptoki-3.24.0/usr/sbin/pkcscca/pkcscca.c:748:5: noescape: Resource "new_key->opaque_attr" is not freed or pointed-to in "memcpy". [Note: The source code implementation of the function has been overridden by a builtin model.]
9. opencryptoki-3.24.0/usr/sbin/pkcscca/pkcscca.c:752:9: leaked_storage: Freeing "new_key" without freeing its pointer field "opaque_attr" leaks the storage that "opaque_attr" points …
```
> proposed patch to fix resource leaks

- testcases/crypto/rsa_func.c
When the CCA token is configure to use CCA AES CIPHER keys, then wrapping such keys is not possible, and an attempt to do so fails with CKR_KEY_NOT_WRAPPABLE. Don't treat this as an error but skip the test.
> testcases: Wrapping CCA AES CIPHER keys can not work, skip it

- testcases/crypto/ec_func.c
Do the memcmp with the right length. Using a wrong length may cause it to overrun the buffers, or compare in a wrong length. Both most likely result in the false assumption that the testcase would have failed, because the two buffers would not be the same.
> TESTCASES: Fix out of bounds access

- usr/lib/cca_stdll/cca_specific.c
In case the pkey ioctl fails, but no MK change is active, break the loop also, otherwise we end up in an endless retry loop.
Fixes: 1d87606113c8ccc673fdc70436da6a94c7b981db
> CCA: Fix endless retry loop in cca_pkey_skey2pkey

- tools/tableidxgen.c
When building this in 2025, it claims Copyright 2025 without any copyright-worthy work happening in that year.
Also note that the number does not have to be updated every year as copyright does not expire for 70+ years.
This patch was done while working on [reproducible builds](https://reproducible-builds.org/) for openSUSE, sponsored by the NLnet NGI0 fund.
> Avoid incorrect copyright claims

- .travis.yml
Running the testcases via ock_tests.sh uses a pipe construct to adjust the output. Without 'set -o pipefail' the return code of this is the return code of the last command in the pipe, but not the return code of ock_tests.sh.
> TRAVIS: Set 'pipefail' to catch the return code of the testcases

- tools/tableidxgen.c
for reproducible builds
This is an alternative to #829
> Drop timestamp from autogenerated files

- testcases/crypto/rsa_func.c
- usr/lib/common/mech_rsa.c
In the CI run a few test vectors failed which have an invalid combination of parameters. Enhance the handling of those cases and skip the tests.
Travis did not show the error due to missing 'pipefile'.
> Fix AESKW testcases

- usr/lib/api/policy.c
Handling for mechanism CKM_IBM_DILITHIUM is missing in function `policy_check_signature_size()`. This causes `policy_update_mech_info()` to remove the `CKF_SIGN` and `CKF_VERIFY` flags when a minimum strength of larger than 0 is configured in the policy config file, because function `policy_check_signature_size()` erroneously returns a signature size of zero, which is below the allowed signature size. Return a signature size of 256 bits instead.
This only affects the mechanism info returned by `C_GetMechanismInfo()`, when the policy defines minimum strength of larger than 0. It does not affect the mechanism execution, nor signature creation or verification.
> POLICY: Fix signature size check for the Dilithium mechanism

- usr/lib/common/h_extern.h
- usr/lib/common/key.c
- usr/lib/ep11_stdll/ep11_specific.c
When unwrapping a private key, the public attributes are also supplied to the key. However, not all public key attributes that can be extracted from the SPKI must be added to the private key.
Add a function parameter to the nnn_priv_unwrap_get_data() functions so that the caller can tell if the public attributes are to be supplied to the template of a private or public key object.
> COMMON: Fix unwrap private keys to supply correct public attributes

- testcases/crypto/ec_func.c
- usr/lib/common/key.c
- usr/lib/common/pkey_utils.c
Add a check that CKA_IBM_PROTKEY_NEVER_EXTRACTABLE can not be modified. Like the other CKA_NEVER_xxx or CKA_ALWAYS_xxx attributes, it is only updated internally (i.e. when CKA_IBM_PROTKEY_EXTRACTABLE is updated), but can not be set from external.
And additional fixes....
> COMMON: CKA_IBM_PROTKEY_NEVER_EXTRACTABLE is read only

- Makefile.am
- testcases/init_token.sh.in
If token initialization fails (e.g. due to a timeout in the 'expect' script), fail the 'make ci-installcheck' entirely. Not failing here will leave the tokens uninitialized, and subsequent tests running against the token will each fail with CKR_USER_PIN_NOT_INITIALIZED, CKR_USER_NOT_LOGGED_IN, or similar.
Also increase the 'expect' timeout from the default (10 seconds) to 30 seconds, to give the pkcsconf tool more time to produce the expected output. Furthermore, clearly show if a timeout has happen.
> CI: Fail early if token initialization fails

- usr/lib/cca_stdll/cca_specific.c
Newer CCA versions might report the version string with CSUACFV or CSUACFQ with keyword STATCCA using a different indicator character after the version information. Ignore the indication character and the remaining data entirely. Only the version information as such is of interest.
> CCA: Adjust CCA host library version detection for newer CCA versions

- usr/sbin/pkcsstats/pkcsstats.c
Only check for the user owner (st_uid) of the SHM to be the expected user, but do not check the group owner (st_gid). If the user has an initial group set, then files created by that user will be owned by its group.
This is in accordance to the code in statistics.c in function statistics_open_shm() where it also just checks the user owner, but not the group owner.
This fixes situations where a statistics SHM was created for a user, but when that user tries to display its statistics, it fails with:
pkcsstats: Failed to open statistics for user 'uuuuuu':
SHM '/var.lib.opencryptoki_stats_nnnn' has wrong mode/owner
Fixes: c12656dd653ed01b66d400253ea92d9614d3d5eb
> PKCSSTATS: Fix SHM owner checking

- usr/lib/cca_stdll/cca_specific.c
The output of the CSUAACM verb with the GET-ROLE keyword is in big endian format, regardless of the architecture. Use endiness conversion functions for integer type fields to make it work on little endian architectures.
Fixes: aa9e7461b70539b99f02b73bbb37997716cd0f3d
> CCA: Fix retrieval of ACP for non-s390x platforms

- man/man1/p11kmip.1.in
- man/man5/p11kmip.conf.5.in
- usr/sbin/p11kmip/p11kmip.c
Contains changes to the man pages and help text for P11KMIP to bring it in line with the terminology used in the spec, mainly removing references to "secret keys" and "public keys' and replacing them with "target keys" and "wrapping keys" instead, respectively.
> P11KMIP: Update man page and help text terminology

- usr/lib/cca_stdll/cca_specific.c
Ensure that the PKEY_MODE default is always PKEY_MODE_DEFAULT, even if no config file exists. Same for AES_KEY_MODE: consistently initialize to AES_KEY_MODE_DATA.
> CCA: fix PKEY_MODE and AES_KEY_MODE defaults

- testcases/misc_tests/events.c
- testcases/pkcs11/destroyobjects.c
- usr/lib/api/socket_client.c
- usr/lib/cca_stdll/cca_specific.c
Newer GCC versions report errors for string initialization where the terminating NULL character does not fit into the target variable.
All the fixed places use non-zero-terminated strings, but add an additional character to make the compiler happy.
> Fix '-Wunterminated-string-initialization' warnings

- usr/sbin/p11kmip/kmipclient/attribute.c
- usr/sbin/p11kmip/kmipclient/kmip.c
- usr/sbin/p11kmip/kmipclient/request.c
- usr/sbin/p11kmip/kmipclient/response.c
- usr/sbin/p11kmip/kmipclient/tls.c
- usr/sbin/p11kmip/p11kmip.c
Mostly trivial changes.
@john-craig Please double check the change in function `get_kmip_usage_mask_p11()` in p11kmip.c.
The Coverity scan reported the following for the construct there:
```
CID 551165: (#1 of 1): Operands don't affect result (CONSTANT_EXPRESSION_RESULT)
result_independent_of_operands: keytype->encrypt_decrypt & (12 /* KMIP_CRY_USAGE_MASK_ENCRYPT | KMIP_CRY_USAGE_MASK_DECRYPT */) is always 0 regardless of the values of its operands. This occurs as the bitwise first operand of "|".
```
I fixed this using a series of explicit if statements. Please check if this produces the intended result.
> P11KMIP: Fix Coverity scan findings

- usr/lib/common/mech_openssl.c
The range check for the AES-CTR counter width is off by a factor of 8.
According to the PKCS#11 standard, counter width is expressed in bits, and the range is supposed to be: 0 < ulCounterBits ≤ 128.
This affects the soft token, as well as the ICA token if the software fallback path is taken.
Closes: https://github.com/opencryptoki/opencryptoki/issues/881
> COMMON: Fix AES-CTR counter width range checking

- testcases/common/common.c
- testcases/crypto/rsa.h
- testcases/crypto/rsa_func.c
- testcases/crypto/rsaupdate_func.c
- testcases/misc_tests/cca_ep11_export_import_test.c
- testcases/misc_tests/reencrypt.c
- testcases/misc_tests/tok2tok_transport.c
- usr/lib/common/utility.c
Add CKM_RSA_X9_31_KEY_PAIR_GEN to function pkcsget_keytype_for_mech() so that a key gen with CKM_RSA_X9_31_KEY_PAIR_GEN can get the key type.
This fixes the EP11 token returning CKR_MECHANISM_INVALID on a key pair gen with CKM_RSA_X9_31_KEY_PAIR_GEN. Currently only the EP11 token supports CKM_RSA_X9_31_KEY_PAIR_GEN at all.
> COMMON/EP11: Fix keygen with CKM_RSA_X9_31_KEY_PAIR_GEN

- usr/sbin/pkcsslotd/pkcsslotd.h
- usr/sbin/pkcsslotd/slotmgr.c
The pkcsslotd uses MD5 to calculate kind of a checksum of the token directory path, for easy checking if the same token directory has already been used by other tokens.
The use of MD5 for this is just historical, and has no security relevance at all. Still, OpenSSL running in FIPS mode might reject the use of MD5, so pkcsslotd will fail to start.
Change the code to use SHA256 instead.
> PKCSSLOTD: Remove the use of MD5

- man/man1/p11sak.1.in
- testcases/misc_tests/p11sak_test.sh
- usr/sbin/p11kmip/p11kmip.c
- usr/sbin/p11sak/p11sak.c
- usr/sbin/p11sak/p11sak.h
- usr/sbin/p11sak/p11sak.mk
- usr/sbin/p11sak/p11sak_keywrap.c
- usr/sbin/p11sak/p11tool.c
- usr/sbin/p11sak/p11tool.h
Add new p11sak commands 'wrap-key' and 'unwrap-key'. These can be used to export and import keys by means of key wrapping/unwrapping.
Several key wrapping mechanisms are supported by p11sak, but the tokens used must also support these mechanisms.
A key object must have CKA_EXTRACTABLE=TRUE to be exportable.
> p11sak: Add wrap-key and unwrap-key commands
